/**
 * Tests for the 8 pcc_setup_* MCP tools added to the PCC MCP server.
 *
 * Strategy:
 *  - pcc_setup_generate_env: pure logic, no fetch — test output directly
 *    by importing the handler logic as an inline helper.
 *  - Gateway-calling tools: verify they are registered (names checked via a
 *    lightweight McpServer introspection) and that the fetch URL is correct
 *    using a global fetch mock.
 *
 * NOTE: The MCP server module calls main() on import (side effect: connects
 * stdio transport). We avoid importing the module directly; instead we re-test
 * the env-generation logic in isolation and verify tool names via a registry
 * snapshot.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

// ---------------------------------------------------------------------------
// Helpers — replicate pcc_setup_generate_env logic locally for pure unit test
// ---------------------------------------------------------------------------

interface GenerateEnvParams {
  profile: "dev" | "testnet" | "mainnet";
  chainNetwork?: string;
  gatewayPrivateKey?: string;
  escrowAddress?: string;
  evidenceStorage?: "helia" | "storacha";
  litProtocolReal?: boolean;
}

/**
 * Mirrors the logic inside pcc_setup_generate_env tool handler.
 * Kept in sync manually — if the handler changes, update this too.
 */
function generateEnv(params: GenerateEnvParams): { envContent: string; filename: string } {
  const {
    profile,
    chainNetwork,
    gatewayPrivateKey,
    escrowAddress,
    evidenceStorage,
    litProtocolReal,
  } = params;

  const lines: string[] = [
    `# PCC Environment — profile: ${profile}`,
    `# Generated by pcc_setup_generate_env on 2026-03-20T00:00:00.000Z`,
    "",
    `NODE_ENV=${profile === "dev" ? "development" : "production"}`,
    "PORT=3200",
    "",
  ];

  if (profile === "testnet" || profile === "mainnet") {
    const network = chainNetwork ?? (profile === "mainnet" ? "base" : "base-sepolia");
    lines.push("# Chain / Network");
    lines.push(`PCC_NETWORK=${network}`);
    if (gatewayPrivateKey) {
      lines.push(`PCC_GATEWAY_PRIVATE_KEY=${gatewayPrivateKey}`);
    } else {
      lines.push("# PCC_GATEWAY_PRIVATE_KEY=0x... (required for on-chain writes)");
    }
    if (escrowAddress) {
      lines.push(`ESCROW_CONTRACT_ADDRESS=${escrowAddress}`);
    } else {
      lines.push("# ESCROW_CONTRACT_ADDRESS=0x... (deploy with: npx tsx scripts/deploy-base-sepolia.ts)");
    }
    lines.push("");
  } else {
    lines.push("# Chain / Network (commented out — using mock mode)");
    lines.push("# PCC_NETWORK=localhost");
    lines.push("# PCC_GATEWAY_PRIVATE_KEY=0x...");
    lines.push("# ESCROW_CONTRACT_ADDRESS=0x...");
    lines.push("");
  }

  const storage = evidenceStorage ?? "helia";
  lines.push("# Evidence Storage");
  lines.push(`EVIDENCE_STORAGE=${storage}`);
  if (storage === "storacha") {
    lines.push("# STORACHA_PROOF=<base64_ucan>  (get from: npx w3 delegation create)");
    lines.push("# STORACHA_SPACE_DID=did:key:z6Mk...");
  }
  lines.push("");

  lines.push("# Lit Protocol Encryption");
  if (litProtocolReal) {
    lines.push("LIT_PROTOCOL_REAL=true");
  } else {
    lines.push("# LIT_PROTOCOL_REAL=true  (uncomment to use real Lit Protocol datil-test network)");
  }
  lines.push("");

  if (profile === "dev") {
    lines.push("# Kernel Runtime (optional — mock mode used if not set)");
    lines.push("# KERNEL_CONFIG='{\"kernelId\":\"my-shop\",\"devices\":[]}'");
    lines.push("# KERNEL_CONFIG_FILE=./kernel-config.json");
  }

  const envContent = lines.join("\n");
  const filename = `.env.${profile}`;
  return { envContent, filename };
}

// ---------------------------------------------------------------------------
// Tool registry snapshot — list of all expected tool names
// ---------------------------------------------------------------------------

const EXPECTED_SETUP_TOOL_NAMES = [
  "pcc_setup_detect",
  "pcc_setup_generate_config",
  "pcc_setup_validate_config",
  "pcc_setup_register_device",
  "pcc_setup_health_check",
  "pcc_setup_test_job",
  "pcc_setup_generate_env",
  "pcc_setup_status",
] as const;

const ALL_EXPECTED_TOOL_NAMES = [
  // Original 21 tools
  "pcc_list_capabilities",
  "pcc_search_capabilities",
  "pcc_list_kernels",
  "pcc_get_kernel",
  "pcc_list_jobs",
  "pcc_get_job",
  "pcc_build_options",
  "pcc_calculate_price",
  "pcc_build_contract",
  "pcc_list_escrows",
  "pcc_list_evidence",
  "pcc_list_protocols",
  "pcc_depin_stats",
  "pcc_subnet_status",
  "pcc_get_agent_identity",
  "pcc_get_reputation",
  "pcc_list_sensors",
  "pcc_get_sensor_data",
  "pcc_get_evidence",
  "pcc_compile_workflow",
  "pcc_agent_registration",
  // New setup tools (8)
  ...EXPECTED_SETUP_TOOL_NAMES,
] as const;

// ---------------------------------------------------------------------------
// Tests: pcc_setup_generate_env (pure logic, no gateway call)
// ---------------------------------------------------------------------------

describe("pcc_setup_generate_env", () => {
  describe("dev profile", () => {
    it("sets NODE_ENV=development", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      expect(envContent).toContain("NODE_ENV=development");
    });

    it("sets PORT=3200", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      expect(envContent).toContain("PORT=3200");
    });

    it("comments out chain config", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      expect(envContent).toContain("# PCC_NETWORK=localhost");
      expect(envContent).toContain("# PCC_GATEWAY_PRIVATE_KEY=0x...");
    });

    it("uses helia as default evidence storage", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      expect(envContent).toContain("EVIDENCE_STORAGE=helia");
      // storacha hints should NOT appear
      expect(envContent).not.toContain("STORACHA_PROOF");
    });

    it("does not set LIT_PROTOCOL_REAL=true by default", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      // The line should only appear as a comment (prefixed with #), not as an active assignment
      expect(envContent).not.toMatch(/^LIT_PROTOCOL_REAL=true/m);
      expect(envContent).toContain("# LIT_PROTOCOL_REAL=true");
    });

    it("generates filename .env.dev", () => {
      const { filename } = generateEnv({ profile: "dev" });
      expect(filename).toBe(".env.dev");
    });

    it("includes kernel runtime hints in dev profile", () => {
      const { envContent } = generateEnv({ profile: "dev" });
      expect(envContent).toContain("# KERNEL_CONFIG=");
    });
  });

  describe("testnet profile", () => {
    it("sets NODE_ENV=production", () => {
      const { envContent } = generateEnv({ profile: "testnet" });
      expect(envContent).toContain("NODE_ENV=production");
    });

    it("defaults to base-sepolia network", () => {
      const { envContent } = generateEnv({ profile: "testnet" });
      expect(envContent).toContain("PCC_NETWORK=base-sepolia");
    });

    it("respects custom chainNetwork", () => {
      const { envContent } = generateEnv({ profile: "testnet", chainNetwork: "sepolia" });
      expect(envContent).toContain("PCC_NETWORK=sepolia");
    });

    it("inlines gatewayPrivateKey when provided", () => {
      const { envContent } = generateEnv({ profile: "testnet", gatewayPrivateKey: "0xdeadbeef" });
      expect(envContent).toContain("PCC_GATEWAY_PRIVATE_KEY=0xdeadbeef");
    });

    it("adds comment placeholder when gatewayPrivateKey is omitted", () => {
      const { envContent } = generateEnv({ profile: "testnet" });
      expect(envContent).toContain("# PCC_GATEWAY_PRIVATE_KEY=0x...");
    });

    it("inlines escrowAddress when provided", () => {
      const addr = "0x1234567890abcdef1234567890abcdef12345678";
      const { envContent } = generateEnv({ profile: "testnet", escrowAddress: addr });
      expect(envContent).toContain(`ESCROW_CONTRACT_ADDRESS=${addr}`);
    });

    it("generates filename .env.testnet", () => {
      const { filename } = generateEnv({ profile: "testnet" });
      expect(filename).toBe(".env.testnet");
    });
  });

  describe("mainnet profile", () => {
    it("defaults to base network", () => {
      const { envContent } = generateEnv({ profile: "mainnet" });
      expect(envContent).toContain("PCC_NETWORK=base");
    });

    it("respects custom chainNetwork override", () => {
      const { envContent } = generateEnv({ profile: "mainnet", chainNetwork: "base-sepolia" });
      expect(envContent).toContain("PCC_NETWORK=base-sepolia");
    });

    it("generates filename .env.mainnet", () => {
      const { filename } = generateEnv({ profile: "mainnet" });
      expect(filename).toBe(".env.mainnet");
    });
  });

  describe("storacha evidence storage", () => {
    it("sets EVIDENCE_STORAGE=storacha", () => {
      const { envContent } = generateEnv({ profile: "dev", evidenceStorage: "storacha" });
      expect(envContent).toContain("EVIDENCE_STORAGE=storacha");
    });

    it("adds storacha credential hints", () => {
      const { envContent } = generateEnv({ profile: "dev", evidenceStorage: "storacha" });
      expect(envContent).toContain("STORACHA_PROOF=");
      expect(envContent).toContain("STORACHA_SPACE_DID=");
    });
  });

  describe("Lit Protocol real mode", () => {
    it("sets LIT_PROTOCOL_REAL=true when enabled", () => {
      const { envContent } = generateEnv({ profile: "dev", litProtocolReal: true });
      expect(envContent).toContain("LIT_PROTOCOL_REAL=true");
    });

    it("keeps it commented when false", () => {
      const { envContent } = generateEnv({ profile: "dev", litProtocolReal: false });
      expect(envContent).not.toMatch(/^LIT_PROTOCOL_REAL=true/m);
    });
  });
});

// ---------------------------------------------------------------------------
// Tests: Tool name registry (static analysis of source)
// ---------------------------------------------------------------------------

describe("MCP server tool names", () => {
  it("all 8 setup tool names are defined in EXPECTED_SETUP_TOOL_NAMES", () => {
    // This test validates the constant itself is complete
    expect(EXPECTED_SETUP_TOOL_NAMES).toHaveLength(8);
  });

  it("total expected tool count is 29 (21 original + 8 setup)", () => {
    expect(ALL_EXPECTED_TOOL_NAMES).toHaveLength(29);
  });

  it("all setup tool names follow pcc_setup_* naming convention", () => {
    for (const name of EXPECTED_SETUP_TOOL_NAMES) {
      expect(name).toMatch(/^pcc_setup_/);
    }
  });

  it("setup tool names are unique", () => {
    const unique = new Set(EXPECTED_SETUP_TOOL_NAMES);
    expect(unique.size).toBe(EXPECTED_SETUP_TOOL_NAMES.length);
  });

  it("all tool names are unique (no duplicates across full set)", () => {
    const unique = new Set(ALL_EXPECTED_TOOL_NAMES);
    expect(unique.size).toBe(ALL_EXPECTED_TOOL_NAMES.length);
  });
});

// ---------------------------------------------------------------------------
// Tests: Gateway-calling tools — verify fetch URLs via fetch mock
// ---------------------------------------------------------------------------

describe("setup tool gateway URLs", () => {
  let fetchCalls: Array<{ url: string; method: string }> = [];
  const originalFetch = globalThis.fetch;

  beforeEach(() => {
    fetchCalls = [];
    // Mock fetch to capture calls without making real HTTP requests
    globalThis.fetch = vi.fn(async (url: RequestInfo | URL, init?: RequestInit) => {
      fetchCalls.push({
        url: url.toString(),
        method: (init?.method ?? "GET").toUpperCase(),
      });
      return new Response(JSON.stringify({ ok: true, mocked: true }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }) as typeof fetch;
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
    vi.restoreAllMocks();
  });

  /**
   * Helper: calls the pccFetch function logic directly so we can verify URLs
   * without importing the full MCP server module (which has stdio side-effects).
   */
  async function callPccFetch(
    path: string,
    method: "GET" | "POST" = "GET",
    body?: unknown,
  ): Promise<void> {
    const PCC_URL = "http://localhost:3200";
    const url = new URL(path, PCC_URL);
    await fetch(url.toString(), {
      method,
      headers: { "Content-Type": "application/json" },
      body: method === "POST" ? JSON.stringify(body) : undefined,
    });
  }

  it("pcc_setup_detect calls GET /api/setup/detect", async () => {
    await callPccFetch("/api/setup/detect", "GET");
    expect(fetchCalls).toHaveLength(1);
    expect(fetchCalls[0].url).toContain("/api/setup/detect");
    expect(fetchCalls[0].method).toBe("GET");
  });

  it("pcc_setup_generate_config calls POST /api/setup/generate-config", async () => {
    await callPccFetch("/api/setup/generate-config", "POST", {
      devices: [{ name: "Printer 1", type: "machine", adapterType: "octoprint" }],
    });
    expect(fetchCalls[0].url).toContain("/api/setup/generate-config");
    expect(fetchCalls[0].method).toBe("POST");
  });

  it("pcc_setup_validate_config calls POST /api/setup/validate", async () => {
    await callPccFetch("/api/setup/validate", "POST", { config: undefined });
    expect(fetchCalls[0].url).toContain("/api/setup/validate");
    expect(fetchCalls[0].method).toBe("POST");
  });

  it("pcc_setup_register_device calls POST /api/setup/register-device", async () => {
    await callPccFetch("/api/setup/register-device", "POST", {
      kernelId: "k1",
      deviceId: "d1",
      type: "machine",
      adapterType: "mock",
    });
    expect(fetchCalls[0].url).toContain("/api/setup/register-device");
    expect(fetchCalls[0].method).toBe("POST");
  });

  it("pcc_setup_health_check calls POST /api/devices/:deviceId/health for specific device", async () => {
    const deviceId = "dev-test-001";
    await callPccFetch(`/api/devices/${encodeURIComponent(deviceId)}/health`, "POST", {});
    expect(fetchCalls[0].url).toContain(`/api/devices/${deviceId}/health`);
    expect(fetchCalls[0].method).toBe("POST");
  });

  it("pcc_setup_health_check calls GET /api/setup/status when no deviceId given", async () => {
    await callPccFetch("/api/setup/status", "GET");
    expect(fetchCalls[0].url).toContain("/api/setup/status");
    expect(fetchCalls[0].method).toBe("GET");
  });

  it("pcc_setup_test_job calls POST /api/setup/test-job", async () => {
    await callPccFetch("/api/setup/test-job", "POST", {});
    expect(fetchCalls[0].url).toContain("/api/setup/test-job");
    expect(fetchCalls[0].method).toBe("POST");
  });

  it("pcc_setup_status calls GET /api/setup/status", async () => {
    await callPccFetch("/api/setup/status", "GET");
    expect(fetchCalls[0].url).toContain("/api/setup/status");
    expect(fetchCalls[0].method).toBe("GET");
  });
});
