/**
 * LO-EV-1 — the canonical signing byte contract (`pcc.evidence.signing-preimage.v1`).
 *
 * Every Ed25519 signature PCC produces or checks over evidence is a signature
 * over bytes built HERE. The contract has three preimages:
 *
 * 1. Digest signature — `signingPreimage(digest)`.
 *    The signed message is the UTF-8 encoding of the tagged digest string
 *    exactly as `util/canonical.ts` produces it: `"sha256:"` followed by 64
 *    lowercase hex characters (71 bytes). It is NOT the 32 raw digest bytes and
 *    carries no extra domain prefix. This is the convention every incumbent
 *    producer and consumer on master already uses (kernel-sdk job handler +
 *    `verifyBundleSignature`, the digital kernels, pcc-node `log_capture`, the
 *    gateway's device-evidence verifier), so pinning it invalidates no
 *    existing signature.
 *
 * 2. Session-key delegation — `sessionKeyDelegationPreimage(sessionKey)`.
 *    UTF-8 of `JSON.stringify` over a FIXED-ORDER object:
 *      sessionId, parentAgentId, publicKey (lowercase hex), issuedAt,
 *      expiresAt, scope{allowedActions, contractIds, maxSignatures},
 *      then derivationPath — present only when defined.
 *    The two arrays are sorted with the JS default sort (UTF-16 code units).
 *    Key order is INSERTION order, not alphabetical: a producer that sorts
 *    keys (e.g. with `canonicalize`) produces different bytes and its
 *    signature will not verify.
 *
 * 3. Session revocation — `sessionRevocationPreimage(revocation)`.
 *    UTF-8 of `JSON.stringify({ sessionId, revokedAt, reason })`.
 *
 * Domain separation: the same Ed25519 key signs both evidence digests and the
 * registration challenge `pcc-kernel-signing-key:<kernelId>`. The two message
 * spaces cannot collide because a digest preimage is always exactly
 * `sha256:<64 hex>`, and verifiers build it only from `parseTaggedDigest`,
 * which rejects every other string.
 *
 * Cross-language reproduction: Python must use
 * `json.dumps(obj, separators=(",", ":"), ensure_ascii=False)` with the same
 * key insertion order, then `.encode("utf-8")`. Golden vectors live in
 * `packages/pcc-node/tests/goldens.json` (generated by `tests/gen_goldens.mjs`).
 */
import type { SHA256 } from "../types/common.js";
import type { SessionKey, SessionRevocation } from "../identity/ephemeral.js";

export const SIGNING_PREIMAGE_CONTRACT = "pcc.evidence.signing-preimage.v1";

/** The only accepted digest form: `sha256:` + 64 lowercase hex characters. */
export const TAGGED_DIGEST_PATTERN = /^sha256:[0-9a-f]{64}$/;

export type SigningPreimageErrorCode =
  | "raw-digest-bytes"
  | "not-a-string"
  | "hex-prefixed-digest"
  | "missing-sha256-tag"
  | "malformed-tagged-digest"
  | "malformed-signature"
  | "malformed-public-key"
  | "malformed-session-key"
  | "malformed-revocation";

export class SigningPreimageError extends Error {
  readonly code: SigningPreimageErrorCode;

  constructor(code: SigningPreimageErrorCode, message: string) {
    super(`${code}: ${message}`);
    this.name = "SigningPreimageError";
    this.code = code;
  }
}

export function isTaggedDigest(value: unknown): value is SHA256 {
  return typeof value === "string" && TAGGED_DIGEST_PATTERN.test(value);
}

/**
 * Accepts only the canonical tagged digest string. Raw digest bytes, `0x`
 * hex, a missing tag, uppercase hex and wrong lengths are each rejected with
 * their own stable code.
 */
export function parseTaggedDigest(value: unknown): SHA256 {
  if (value instanceof Uint8Array) {
    throw new SigningPreimageError(
      "raw-digest-bytes",
      "raw digest bytes are not a signing preimage; pass the tagged sha256: string",
    );
  }
  if (typeof value !== "string") {
    throw new SigningPreimageError("not-a-string", `expected a tagged digest string, got ${typeof value}`);
  }
  if (/^0x/i.test(value)) {
    throw new SigningPreimageError("hex-prefixed-digest", "0x-prefixed hex is not the evidence digest form");
  }
  if (!value.startsWith("sha256:")) {
    throw new SigningPreimageError("missing-sha256-tag", "digest must start with 'sha256:'");
  }
  if (!TAGGED_DIGEST_PATTERN.test(value)) {
    throw new SigningPreimageError(
      "malformed-tagged-digest",
      "digest must be 'sha256:' followed by exactly 64 lowercase hex characters",
    );
  }
  return value as SHA256;
}

/** The bytes an evidence digest signature covers (see contract item 1). */
export function signingPreimage(digest: unknown): Uint8Array {
  return new TextEncoder().encode(parseTaggedDigest(digest));
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function parseFixedHex(
  value: unknown,
  byteLength: number,
  code: "malformed-signature" | "malformed-public-key",
): Uint8Array {
  if (typeof value !== "string") {
    throw new SigningPreimageError(code, `expected a hex string, got ${typeof value}`);
  }
  const hex = value.startsWith("0x") || value.startsWith("0X") ? value.slice(2) : value;
  if (!new RegExp(`^[0-9a-fA-F]{${byteLength * 2}}$`).test(hex)) {
    throw new SigningPreimageError(code, `expected ${byteLength} bytes as ${byteLength * 2} hex characters`);
  }
  return hexToBytes(hex);
}

/** A detached Ed25519 signature: 64 bytes as 128 hex chars, optional `0x`. */
export function parseEd25519SignatureHex(value: unknown): Uint8Array {
  return parseFixedHex(value, 64, "malformed-signature");
}

/** A raw Ed25519 public key: 32 bytes as 64 hex chars, optional `0x`. */
export function parseEd25519PublicKeyHex(value: unknown): Uint8Array {
  return parseFixedHex(value, 32, "malformed-public-key");
}

function isNonNegativeSafeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((v) => typeof v === "string");
}

/** The bytes a principal signs to authorize a session key (contract item 2). */
export function sessionKeyDelegationPreimage(
  sessionKey: Omit<SessionKey, "parentSignature">,
): Uint8Array {
  const sk = sessionKey;
  if (
    typeof sk.sessionId !== "string" ||
    typeof sk.parentAgentId !== "string" ||
    !(sk.publicKey instanceof Uint8Array) ||
    sk.publicKey.length !== 32 ||
    !isNonNegativeSafeInteger(sk.issuedAt) ||
    !isNonNegativeSafeInteger(sk.expiresAt) ||
    !sk.scope ||
    !isStringArray(sk.scope.allowedActions) ||
    !isStringArray(sk.scope.contractIds) ||
    !isNonNegativeSafeInteger(sk.scope.maxSignatures) ||
    (sk.derivationPath !== undefined && typeof sk.derivationPath !== "string")
  ) {
    throw new SigningPreimageError(
      "malformed-session-key",
      "session key fields do not match the delegation contract",
    );
  }
  const body: Record<string, unknown> = {
    sessionId: sk.sessionId,
    parentAgentId: sk.parentAgentId,
    publicKey: toHex(sk.publicKey),
    issuedAt: sk.issuedAt,
    expiresAt: sk.expiresAt,
    scope: {
      allowedActions: [...sk.scope.allowedActions].sort(),
      contractIds: [...sk.scope.contractIds].sort(),
      maxSignatures: sk.scope.maxSignatures,
    },
  };
  if (sk.derivationPath !== undefined) {
    body.derivationPath = sk.derivationPath;
  }
  return new TextEncoder().encode(JSON.stringify(body));
}

/** The bytes a principal signs to revoke a session key (contract item 3). */
export function sessionRevocationPreimage(
  revocation: Omit<SessionRevocation, "parentSignature">,
): Uint8Array {
  const r = revocation;
  if (
    typeof r.sessionId !== "string" ||
    !isNonNegativeSafeInteger(r.revokedAt) ||
    typeof r.reason !== "string"
  ) {
    throw new SigningPreimageError(
      "malformed-revocation",
      "revocation fields do not match the revocation contract",
    );
  }
  return new TextEncoder().encode(
    JSON.stringify({ sessionId: r.sessionId, revokedAt: r.revokedAt, reason: r.reason }),
  );
}
