"""LO-EV-1 signing byte contract (``pcc.evidence.signing-preimage.v1``), Python side.

Mirror of ``packages/spec/src/evidence/signing-preimage.ts``. Both
implementations are pinned to ``tests/goldens.json`` (generated by
``tests/gen_goldens.mjs``), so any drift fails CI in both languages.

1. Digest signature: the signed message is the UTF-8 encoding of the tagged
   digest string ``"sha256:" + 64 lowercase hex`` (71 bytes) -- never the 32
   raw digest bytes, never a 0x form.
2. Session-key delegation: UTF-8 of compact JSON over a FIXED-ORDER object
   (sessionId, parentAgentId, publicKey hex, issuedAt, expiresAt,
   scope{allowedActions, contractIds, maxSignatures}, then derivationPath only
   when present). Key order is insertion order, not sorted.
3. Session revocation: UTF-8 of compact JSON ``{sessionId, revokedAt, reason}``.

Two ECMAScript behaviours are reproduced on purpose:
- JS ``$`` never matches before a trailing newline, so digests are checked
  with ``fullmatch`` (Python's ``$`` would accept ``"sha256:...\\n"``).
- JS ``Array.prototype.sort`` orders strings by UTF-16 code units, so the
  scope arrays are sorted on their UTF-16-BE encoding.
"""

import json
import re

SIGNING_PREIMAGE_CONTRACT = "pcc.evidence.signing-preimage.v1"

_TAGGED_DIGEST = re.compile(r"sha256:[0-9a-f]{64}")
_MAX_SAFE_INTEGER = 2 ** 53 - 1


class SigningPreimageError(ValueError):
    """Contract violation; ``code`` matches the TypeScript error codes."""

    def __init__(self, code, message):
        super().__init__(code + ": " + message)
        self.code = code


def is_tagged_digest(value):
    return isinstance(value, str) and _TAGGED_DIGEST.fullmatch(value) is not None


def parse_tagged_digest(value):
    if isinstance(value, (bytes, bytearray, memoryview)):
        raise SigningPreimageError(
            "raw-digest-bytes",
            "raw digest bytes are not a signing preimage; pass the tagged sha256: string",
        )
    if not isinstance(value, str):
        raise SigningPreimageError(
            "not-a-string", "expected a tagged digest string, got " + type(value).__name__
        )
    if value[:2] in ("0x", "0X"):
        raise SigningPreimageError("hex-prefixed-digest", "0x-prefixed hex is not the evidence digest form")
    if not value.startswith("sha256:"):
        raise SigningPreimageError("missing-sha256-tag", "digest must start with 'sha256:'")
    if _TAGGED_DIGEST.fullmatch(value) is None:
        raise SigningPreimageError(
            "malformed-tagged-digest",
            "digest must be 'sha256:' followed by exactly 64 lowercase hex characters",
        )
    return value


def signing_preimage(digest):
    """The bytes an evidence digest signature covers."""
    return parse_tagged_digest(digest).encode("utf-8")


def _parse_fixed_hex(value, byte_length, code):
    if not isinstance(value, str):
        raise SigningPreimageError(code, "expected a hex string, got " + type(value).__name__)
    hex_part = value[2:] if value[:2] in ("0x", "0X") else value
    if re.fullmatch("[0-9a-fA-F]{%d}" % (byte_length * 2), hex_part) is None:
        raise SigningPreimageError(
            code, "expected %d bytes as %d hex characters" % (byte_length, byte_length * 2)
        )
    return bytes.fromhex(hex_part)


def parse_ed25519_signature_hex(value):
    return _parse_fixed_hex(value, 64, "malformed-signature")


def parse_ed25519_public_key_hex(value):
    return _parse_fixed_hex(value, 32, "malformed-public-key")


def _is_safe_uint(value):
    # bool is an int subclass in Python; JSON would render it true/false.
    return (
        isinstance(value, int)
        and not isinstance(value, bool)
        and 0 <= value <= _MAX_SAFE_INTEGER
    )


def _is_str_list(value):
    return isinstance(value, list) and all(isinstance(v, str) for v in value)


def _js_sorted(strings):
    return sorted(strings, key=lambda s: s.encode("utf-16-be"))


def _compact_json(obj):
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False)


def session_key_delegation_preimage(session_key):
    """The bytes a principal signs to authorize a session key.

    ``session_key`` is a dict with ``publicKey`` as 32 raw bytes. An absent
    ``derivationPath`` key corresponds to TypeScript ``undefined``.
    """
    sk = session_key
    scope = sk.get("scope") if isinstance(sk, dict) else None
    ok = (
        isinstance(sk, dict)
        and isinstance(sk.get("sessionId"), str)
        and isinstance(sk.get("parentAgentId"), str)
        and isinstance(sk.get("publicKey"), (bytes, bytearray))
        and len(sk["publicKey"]) == 32
        and _is_safe_uint(sk.get("issuedAt"))
        and _is_safe_uint(sk.get("expiresAt"))
        and isinstance(scope, dict)
        and _is_str_list(scope.get("allowedActions"))
        and _is_str_list(scope.get("contractIds"))
        and _is_safe_uint(scope.get("maxSignatures"))
        and ("derivationPath" not in sk or isinstance(sk["derivationPath"], str))
    )
    if not ok:
        raise SigningPreimageError(
            "malformed-session-key", "session key fields do not match the delegation contract"
        )
    body = {
        "sessionId": sk["sessionId"],
        "parentAgentId": sk["parentAgentId"],
        "publicKey": bytes(sk["publicKey"]).hex(),
        "issuedAt": sk["issuedAt"],
        "expiresAt": sk["expiresAt"],
        "scope": {
            "allowedActions": _js_sorted(scope["allowedActions"]),
            "contractIds": _js_sorted(scope["contractIds"]),
            "maxSignatures": scope["maxSignatures"],
        },
    }
    if "derivationPath" in sk:
        body["derivationPath"] = sk["derivationPath"]
    return _compact_json(body).encode("utf-8")


def session_revocation_preimage(revocation):
    """The bytes a principal signs to revoke a session key."""
    r = revocation
    if not (
        isinstance(r, dict)
        and isinstance(r.get("sessionId"), str)
        and _is_safe_uint(r.get("revokedAt"))
        and isinstance(r.get("reason"), str)
    ):
        raise SigningPreimageError(
            "malformed-revocation", "revocation fields do not match the revocation contract"
        )
    return _compact_json(
        {"sessionId": r["sessionId"], "revokedAt": r["revokedAt"], "reason": r["reason"]}
    ).encode("utf-8")
