#!/usr/bin/env python3
"""Generate the Unicode case-folding table the gateway's identity comparison uses.

WP-A round 8 (astra, authz r2: "lower -> upper -> lower is not full Unicode case
folding; it equates dotless i with ASCII i").

Unicode full case folding (CaseFolding.txt, statuses C + F) equals the default
lowercase mapping for every code point EXCEPT a small set of lowercase or uncased
characters that fold further: sharp s to "ss", final sigma to sigma, long s to "s",
Cherokee small letters to their capitals, and a few more. JavaScript has
toLowerCase() but no case fold. So the gateway applies toLowerCase() and then this
table: auth/casefold.ts caseFold().

Python's str.casefold() implements full case folding. This script:
  1. builds TABLE = { c: c.casefold() } for every c with c.lower() == c and
     c.casefold() != c;
  2. checks the construction: for EVERY code point and for final-sigma
     strings, "".join(TABLE.get(ch, ch) for ch in s.lower()) == s.casefold();
  3. writes packages/gateway/src/auth/casefold-table.ts (the table, ASCII-only
     source) and packages/gateway/src/__tests__/fixtures/casefold-golden.json
     (every ASSIGNED code point whose fold changes it, with its expected fold).

Code points added after this Python's Unicode version fold to their lowercase:
their CaseFolding C entry equals their lowercase mapping. Run from the repo
root: python3 packages/gateway/scripts/gen-casefold-table.py
"""
import json
import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # packages/gateway
TABLE_TS = os.path.join(ROOT, "src", "auth", "casefold-table.ts")
GOLDEN = os.path.join(ROOT, "src", "__tests__", "fixtures", "casefold-golden.json")


def code_points():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


table = {}
for cp in code_points():
    c = chr(cp)
    if c.lower() == c and c.casefold() != c:
        table[c] = c.casefold()


def fold(s):
    return "".join(table.get(ch, ch) for ch in s.lower())


bad = [cp for cp in code_points() if fold(chr(cp)) != chr(cp).casefold()]
for s in ["ΑΣ", "ΟΔΟΣ ΟΔΟΣ", "Σ", "ΣΑ", "ᾼΣ", "İstanbul", "STRASSE", "Straße", "ẞ"]:
    if fold(s) != s.casefold():
        bad.append(s)
if bad:
    sys.exit(f"construction check FAILED for {len(bad)} inputs, first: {bad[:5]!r}")


def js_escape(s):
    out = []
    for ch in s:
        cp = ord(ch)
        if 0x20 <= cp < 0x7F and ch not in "\\\"":
            out.append(ch)
        elif cp <= 0xFFFF:
            out.append("\\u%04x" % cp)
        else:
            out.append("\\u{%x}" % cp)
    return "".join(out)


lines = [
    "// GENERATED by packages/gateway/scripts/gen-casefold-table.py: do not edit by hand.",
    f"// Source: Python {sys.version.split()[0]} str.casefold(), Unicode {unicodedata.unidata_version}.",
    "// The folds that go BEYOND the default lowercase mapping (full case folding, C + F).",
    f"// {len(table)} entries. Checked: toLowerCase() then this table equals casefold() for",
    "// every code point (see the script).",
    "export const CASEFOLD_BEYOND_LOWER: ReadonlyMap<string, string> = new Map<string, string>([",
]
for k in sorted(table, key=ord):
    lines.append(f'  ["{js_escape(k)}", "{js_escape(table[k])}"],')
lines.append("]);")
with open(TABLE_TS, "w", encoding="ascii") as f:
    f.write("\n".join(lines) + "\n")

golden = {}
for cp in code_points():
    c = chr(cp)
    if unicodedata.category(c) == "Cn":
        continue  # unassigned in this Unicode version: the JS engine may know it
    if c.casefold() != c:
        golden["%x" % cp] = [ord(x) for x in c.casefold()]
os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
with open(GOLDEN, "w", encoding="ascii") as f:
    json.dump({"unicode": unicodedata.unidata_version, "folds": golden}, f, separators=(",", ":"), sort_keys=True)
    f.write("\n")
print(f"table {len(table)} entries -> {TABLE_TS}")
print(f"golden {len(golden)} code points -> {GOLDEN}")
