/**
 * Postgres synchronous-replication configuration generator.
 *
 * Per scope §5.1 + §14 Q3, Phase 1 uses Postgres' built-in synchronous
 * replication rather than running our own Raft. This module generates
 * the `postgresql.conf` snippet that wires up `synchronous_commit =
 * remote_apply` for the IndexedTool / aggregator_registry tables.
 *
 * Operational summary (from §5.1):
 *   - One primary + N read replicas per mesh
 *   - synchronous_commit = remote_apply ensures the primary waits for
 *     the nearest follower to apply the WAL record before acking
 *   - FIRST 1 (...) means we need quorum of 2-of-3 nodes for writes
 *
 * This module produces config; it does NOT apply it. The deploy
 * pipeline (or operator) applies the snippet.
 */

export interface PostgresSyncConfigOpts {
  /**
   * Logical names of standby servers (must match `application_name` in
   * each standby's `primary_conninfo`). Order matters — the first
   * reachable one becomes the sync standby.
   */
  standbyNames: string[];
  /**
   * Number of standbys that must ack before a commit returns.
   * Defaults to 1 (smallest safe quorum for a 3-node mesh).
   */
  syncRequiredCount?: number;
  /**
   * Tables the sync replication applies to. Phase 1 default covers the
   * federation runtime's hot path. Add tables as the federation
   * surface area grows.
   */
  tables?: string[];
  /**
   * Per-tenant write timeout in ms. If the sync standby doesn't ack
   * within this window, the primary errors the commit. Default 5000.
   */
  syncCommitTimeoutMs?: number;
}

/**
 * Tables included in the default Phase 1 sync-replication scope. Mostly
 * the aggregator's IndexedTool / namespace / ACL state.
 */
export const DEFAULT_SYNC_TABLES = [
  "indexed_tools",
  "indexed_tool_replicas",
  "namespaces",
  "namespace_acls",
  "aggregator_registry",
];

/**
 * Generate a postgresql.conf snippet that enables synchronous
 * replication for the federation runtime's hot-write path.
 *
 * The snippet is idempotent: re-applying yields the same effect. The
 * caller is expected to insert it into `postgresql.conf` (typically via
 * a Railway "Custom postgres conf" override) and reload.
 *
 * Returns the snippet as a multi-line string ready to append.
 */
export function generatePostgresSyncConfig(
  opts: PostgresSyncConfigOpts,
): string {
  if (opts.standbyNames.length === 0) {
    throw new Error(
      "generatePostgresSyncConfig requires at least one standby name",
    );
  }
  const syncCount = opts.syncRequiredCount ?? 1;
  if (syncCount < 1 || syncCount > opts.standbyNames.length) {
    throw new Error(
      `syncRequiredCount must be between 1 and standbyNames.length (got ${syncCount}, ${opts.standbyNames.length} standbys)`,
    );
  }
  const timeoutMs = opts.syncCommitTimeoutMs ?? 5000;
  const tables = opts.tables ?? DEFAULT_SYNC_TABLES;

  const standbyList = opts.standbyNames.map((n) => `"${n}"`).join(", ");

  return [
    "# === @pcc/federation Phase 1: Postgres synchronous replication ===",
    "# Generated by generatePostgresSyncConfig() — do not edit by hand",
    "# Scope: ai/scoping/4-level-federation-2026-05-23.md §5.1",
    "",
    "# Wait for the nearest standby to apply the WAL record before acking commit.",
    "synchronous_commit = remote_apply",
    "",
    `# Sync ${syncCount}-of-${opts.standbyNames.length} standby quorum`,
    `synchronous_standby_names = 'FIRST ${syncCount} (${standbyList})'`,
    "",
    `# Hard cap on how long the primary waits for sync standby ack (ms)`,
    `statement_timeout = ${timeoutMs}`,
    "",
    "# Logical replication enabled — required for the Phase 2 CDC consumer.",
    "wal_level = logical",
    "max_replication_slots = 16",
    "max_wal_senders = 16",
    "",
    "# Tables under federation control (informational; rep is per-cluster, not per-table):",
    ...tables.map((t) => `#   - ${t}`),
    "",
    "# === end @pcc/federation Phase 1 ===",
  ].join("\n");
}

/**
 * Parse `synchronous_standby_names` back into its standby-name list.
 * Used by the lag monitor to know which standbys to probe.
 *
 * Accepts the FIRST N (name1, name2, ...) form as well as the simpler
 * comma-separated form for backward compat with older Postgres setups.
 */
export function parseStandbyNames(value: string): string[] {
  // FIRST N (name1, name2, ...)
  const firstMatch = value.match(/FIRST\s+\d+\s*\(([^)]*)\)/i);
  if (firstMatch) {
    return splitCsv(firstMatch[1]!);
  }
  // ANY N (name1, name2, ...)
  const anyMatch = value.match(/ANY\s+\d+\s*\(([^)]*)\)/i);
  if (anyMatch) {
    return splitCsv(anyMatch[1]!);
  }
  // Plain CSV
  return splitCsv(value);
}

function splitCsv(s: string): string[] {
  return s
    .split(",")
    .map((p) => p.trim().replace(/^["']|["']$/g, ""))
    .filter((p) => p.length > 0);
}
