// SPDX-License-Identifier: MIT
// Code generated by packages/contracts/script/codegen/gen-role-tags.ts. DO NOT EDIT.
// Single source of truth: @pcc/spec/payouts (CONTRIBUTOR_ROLES + keccak256).
// Regenerate via `pnpm --filter @pcc/contracts gen:role-tags`.
pragma solidity ^0.8.24;

/// @title  RoleTags — canonical bytes32 keccak256 role tags for MilestoneEscrow
/// @notice Mirrors the off-chain @pcc/spec ROLE_TAGS map. Drift between the two
///         sides is a CI-detectable bug (RoleTagsCodegen.t.sol).
/// @dev    These constants are referenced by Payout.roleTag in MilestoneEscrow.
library RoleTags {
    bytes32 internal constant OPERATOR = 0x46a52cf33029de9f84853745a87af28464c80bf0346df1b32e205fc73319f622;  // keccak256("operator")
    bytes32 internal constant VERIFIER = 0xd8d69c1da829f8277e4e80945a974b3ca009835eb268c14bf9321952f1cf169e;  // keccak256("verifier")
    bytes32 internal constant INSURER = 0xdd07565b4734c0f203b03129e8ba72db5212faed44f5f1bb16c55bc8e61b4776;  // keccak256("insurer")
    bytes32 internal constant INTEGRATOR = 0x7fca04c084f97ed662fee1aeb0c969285c1557298812941e9d0396b1dc9b7b25;  // keccak256("integrator")
    bytes32 internal constant PROTOCOL_AUTHOR = 0x95de062b85e2e98a62a61651461fd82c56077c29fbcef37dea8220c3107deb73;  // keccak256("protocol-author")
    bytes32 internal constant MODEL_AUTHOR = 0xa61eb7616be58c63a0e71aba4b17c674cafbfb620390674cee37039ab87937e5;  // keccak256("model-author")
    bytes32 internal constant DATASET_CONTRIBUTOR = 0xf3304bcfb6261b2e829765765ae916cf25dddf25c8a6f448dcba3ac9b1494597;  // keccak256("dataset-contributor")
    bytes32 internal constant CURATOR = 0x8b8b3fd2ff17638092aa002125df632689f3f241d0a395d3601646fb8c9ed982;  // keccak256("curator")
    bytes32 internal constant ASSEMBLER = 0x3e0c16759b6b7ab14470ec3e86e85f014269e3f25733036443ab3bf25f2088a2;  // keccak256("assembler")
    bytes32 internal constant NETWORK_TREASURY = 0x863dda834f3fb3b3471c2480ce1a1291284cd22c28f7da25137fe859f0fe075a;  // keccak256("network-treasury")
}
