"""Python<->TS hash parity + Ed25519 signing tests for the #52 log producer.

``goldens.json`` is generated by ``tests/gen_goldens.mjs`` from the VERBATIM
``canonicalize()`` of ``packages/spec/src/util/canonical.ts``. A mismatch on ANY
vector is a BLOCKER: the settlement lane is worthless if the producer's hashes
do not byte-match the TS verifier.

Regenerate goldens after any canonical.ts change:
    node packages/pcc-node/tests/gen_goldens.mjs
"""

import hashlib
import json
from pathlib import Path

import pytest

from pcc_node import log_capture
from pcc_node.log_capture import (
    GENESIS,
    LogCapture,
    LogSigningRefused,
    canonicalize,
    compute_entry_hash,
    _HAS_NACL,
)

_HERE = Path(__file__).resolve().parent
_GOLDENS = _HERE / "goldens.json"

# The oracle's existing golden (pcc-oracle log-chain-parity.test.ts:51) for
# computeLogEntryHash("hello", "cups://job-1", "2026-07-09T00:00:00.000Z").
ORACLE_SHARED_EXPECTED = (
    "sha256:c31408369756b766d5ee02b1403cbee4ab64ed39f9c3de0b7bee4605fdf3d9cd"
)
ORACLE_SHARED_RAW = "hello"
ORACLE_SHARED_SOURCE = "cups://job-1"
ORACLE_SHARED_CAP = "2026-07-09T00:00:00.000Z"

# Deterministic Ed25519 seed for signing round-trip tests (32 bytes).
SEED_HEX = "deadbeef" * 8

_skip_no_nacl = pytest.mark.skipif(not _HAS_NACL, reason="pynacl required")


def _load_goldens():
    # UTF-8 is MANDATORY: on Windows the default open() encoding is cp1252 and
    # would corrupt the non-ASCII / emoji fixtures before they reach the hasher.
    with open(_GOLDENS, encoding="utf-8") as f:
        return json.load(f)


_GOLDENS_DATA = _load_goldens()


def _seed_pubkey_hex():
    import nacl.signing
    import nacl.encoding

    sk = nacl.signing.SigningKey(bytes.fromhex(SEED_HEX))
    return sk.verify_key.encode(nacl.encoding.HexEncoder).decode("ascii")


# ---------------------------------------------------------------------------
# Parity — the money seam (BLOCKER on any mismatch)
# ---------------------------------------------------------------------------

def test_goldens_file_present():
    assert _GOLDENS.exists(), "goldens.json missing -- run: node tests/gen_goldens.mjs"


@pytest.mark.parametrize(
    "g", _GOLDENS_DATA["entry_hash"], ids=lambda g: g["name"]
)
def test_entry_hash_parity(g):
    got = compute_entry_hash(g["rawContent"], g["source"], g["capturedAt"])
    canonical = canonicalize(
        {"capturedAt": g["capturedAt"], "rawContent": g["rawContent"], "source": g["source"]}
    )
    assert got == g["expected"], (
        f"[{g['name']}] Python entryHash != TS golden.\n"
        f"  canonical(py) = {canonical!r}\n"
        f"  got      = {got}\n  expected = {g['expected']}"
    )


@pytest.mark.parametrize(
    "g", _GOLDENS_DATA["canonical"], ids=lambda g: g["name"]
)
def test_canonicalize_string_parity(g):
    got = canonicalize(g["value"])
    assert got == g["expected"], (
        f"[{g['name']}] Python canonicalize != TS canonicalize.\n"
        f"  got      = {got!r}\n  expected = {g['expected']!r}"
    )


def test_oracle_shared_vector_triple_lock():
    """oracle test == gen_goldens.mjs == Python, all on one vector."""
    # 1) Python reproduces the oracle's hardcoded golden directly.
    got = compute_entry_hash(ORACLE_SHARED_RAW, ORACLE_SHARED_SOURCE, ORACLE_SHARED_CAP)
    assert got == ORACLE_SHARED_EXPECTED
    # 2) The TS goldens file carries exactly this vector + digest.
    shared = next(
        g for g in _GOLDENS_DATA["entry_hash"] if g["name"] == "ascii_oracle_shared_vector"
    )
    assert shared["expected"] == ORACLE_SHARED_EXPECTED
    assert shared["rawContent"] == ORACLE_SHARED_RAW
    assert shared["source"] == ORACLE_SHARED_SOURCE
    assert shared["capturedAt"] == ORACLE_SHARED_CAP


def test_genesis_hash():
    assert GENESIS == "sha256:" + "0" * 64


def test_forward_slash_not_escaped():
    # Guards the most common divergence source: a URL-ish string must NOT escape /.
    assert canonicalize("cups://job/1") == '"cups://job/1"'


# ---------------------------------------------------------------------------
# Ed25519 signing + chain (real pynacl)
# ---------------------------------------------------------------------------

@_skip_no_nacl
def test_signer_shape_and_construction():
    pub_hex = _seed_pubkey_hex()
    cap = LogCapture("0x" + pub_hex, SEED_HEX)
    assert cap.signer == "0x" + pub_hex.lower()
    assert len(pub_hex) == 64  # raw 32-byte ed25519 pubkey, hex


@_skip_no_nacl
def test_chain_linkage_and_signatures_verify():
    import nacl.signing
    import nacl.exceptions

    pub_hex = _seed_pubkey_hex()
    vk = nacl.signing.SigningKey(bytes.fromhex(SEED_HEX)).verify_key
    cap = LogCapture("0x" + pub_hex, SEED_HEX)

    e0 = cap.capture("hello", "cups://job-1", "2026-07-09T00:00:00.000Z")
    e1 = cap.capture("world", "cups://job-1", "2026-07-09T00:01:00.000Z")
    p0, p1 = e0["payload"], e1["payload"]

    # Event envelope (WIRE SHAPE 3).
    assert e0["type"] == "log_hash_chain_entry"
    assert e0["timestamp"] == "2026-07-09T00:00:00.000Z"  # defaults to capturedAt

    # Chain linkage: first -> GENESIS, second -> first entryHash.
    assert p0["previousHash"] == GENESIS
    assert p1["previousHash"] == p0["entryHash"]

    # entryHash recompute matches (mirrors verifyLogChain check #1).
    assert p0["entryHash"] == compute_entry_hash("hello", "cups://job-1", "2026-07-09T00:00:00.000Z")
    assert p1["entryHash"] == compute_entry_hash("world", "cups://job-1", "2026-07-09T00:01:00.000Z")

    # kernelSignature shape (WIRE SHAPE 2/3).
    for p in (p0, p1):
        ks = p["kernelSignature"]
        assert ks["algorithm"] == "ed25519"
        assert ks["signer"] == "0x" + pub_hex.lower()
        assert len(ks["value"]) == 128  # 64-byte detached sig, hex

    # The signature verifies over the UTF-8 bytes of the entryHash STRING
    # (no EIP-191 / domain prefix) -- exactly what the oracle checks with noble.
    vk.verify(p0["entryHash"].encode("utf-8"), bytes.fromhex(p0["kernelSignature"]["value"]))
    vk.verify(p1["entryHash"].encode("utf-8"), bytes.fromhex(p1["kernelSignature"]["value"]))

    # A signature does NOT verify over a different message (tamper caught).
    with pytest.raises(nacl.exceptions.BadSignatureError):
        vk.verify((GENESIS).encode("utf-8"), bytes.fromhex(p0["kernelSignature"]["value"]))


@_skip_no_nacl
def test_redacted_omits_raw_content_but_keeps_hash_and_sig():
    import nacl.signing

    pub_hex = _seed_pubkey_hex()
    vk = nacl.signing.SigningKey(bytes.fromhex(SEED_HEX)).verify_key
    cap = LogCapture("0x" + pub_hex, SEED_HEX)

    ev = cap.capture(
        "secret payload", "cups://job-9", "2026-07-09T00:05:00.000Z", redacted=True
    )
    p = ev["payload"]
    assert "rawContent" not in p  # disclosure:redacted-commit
    # entryHash STILL commits to the real content, and the signature verifies.
    assert p["entryHash"] == compute_entry_hash(
        "secret payload", "cups://job-9", "2026-07-09T00:05:00.000Z"
    )
    vk.verify(p["entryHash"].encode("utf-8"), bytes.fromhex(p["kernelSignature"]["value"]))


# ---------------------------------------------------------------------------
# The HMAC dev fallback MUST be refused on the signing path (money path)
# ---------------------------------------------------------------------------

def test_signing_refuses_when_pynacl_absent(monkeypatch):
    """pynacl unavailable -> refuse to sign (never emit an HMAC as ed25519)."""
    monkeypatch.setattr(log_capture, "_HAS_NACL", False)
    with pytest.raises(LogSigningRefused):
        log_capture.sign_ed25519_utf8("sha256:" + "0" * 64, "0x" + "ab" * 32, "cd" * 32)
    with pytest.raises(LogSigningRefused):
        LogCapture("0x" + "ab" * 32, "cd" * 32)


@_skip_no_nacl
def test_signing_refuses_real_hmac_fallback_key(monkeypatch):
    """A genuine crypto.py HMAC-fallback key (public = sha256(secret)) is refused
    EVEN WITH pynacl available: the ed25519 public derived from the secret does
    not match, so signing would emit a signer that fails the oracle's match rule.
    """
    import pcc_node.crypto as crypto_mod

    monkeypatch.setattr(crypto_mod, "_HAS_NACL", False)
    pub, sec = crypto_mod.generate_node_keys()  # HMAC fallback shape
    # Confirm this really is the fallback shape: public == sha256(secret).
    assert pub == hashlib.sha256(bytes.fromhex(sec)).hexdigest()

    with pytest.raises(LogSigningRefused):
        LogCapture("0x" + pub, sec)
    with pytest.raises(LogSigningRefused):
        log_capture.sign_ed25519_utf8("sha256:" + "0" * 64, pub, sec)
