"""LO-EV-1 signing byte contract: Python reproduces the TS goldens byte for byte.

``goldens.json`` is generated by ``tests/gen_goldens.mjs`` (a logic mirror of
``packages/spec/src/evidence/signing-preimage.ts``); the spec package checks
the same file against the real TS helper. Ed25519 is deterministic, so equal
signature bytes here prove pynacl and node:crypto sign identical preimages.

Regenerate goldens after a contract change:
    node packages/pcc-node/tests/gen_goldens.mjs
"""

import json
from pathlib import Path

import pytest

from pcc_node.signing_preimage import (
    SIGNING_PREIMAGE_CONTRACT,
    SigningPreimageError,
    is_tagged_digest,
    parse_ed25519_public_key_hex,
    parse_ed25519_signature_hex,
    parse_tagged_digest,
    session_key_delegation_preimage,
    session_revocation_preimage,
    signing_preimage,
)

_GOLDENS = json.loads((Path(__file__).parent / "goldens.json").read_text(encoding="utf-8"))
DIGEST = "sha256:" + "0123456789abcdef" * 4


def _session_from_golden(g):
    s = dict(g["session"])
    s["publicKey"] = bytes.fromhex(s.pop("publicKeyHex"))
    return s


def _code(fn, *args):
    with pytest.raises(SigningPreimageError) as exc:
        fn(*args)
    return exc.value.code


@pytest.fixture
def nacl():
    """PyNaCl, for the signature half only. Byte parity never needs it, so a
    missing PyNaCl skips just the signature checks, visibly, never the module."""
    signing = pytest.importorskip("nacl.signing", reason="PyNaCl is needed for the signature half")
    exceptions = pytest.importorskip("nacl.exceptions", reason="PyNaCl is needed for the signature half")
    return signing, exceptions


def _verifies(nacl, public_key_hex, message, signature_hex):
    signing, exceptions = nacl
    try:
        signing.VerifyKey(bytes.fromhex(public_key_hex)).verify(message, bytes.fromhex(signature_hex))
        return True
    except exceptions.BadSignatureError:
        return False


def test_contract_version_matches_ts():
    assert SIGNING_PREIMAGE_CONTRACT == "pcc.evidence.signing-preimage.v1"


def test_goldens_carry_all_contract_sections():
    for section in ("signing_preimage", "session_delegation", "session_revocation"):
        assert _GOLDENS.get(section), "goldens.json lacks %s -- run gen_goldens.mjs" % section


@pytest.mark.parametrize("g", _GOLDENS["signing_preimage"], ids=lambda g: g["name"])
def test_signing_preimage_parity(g):
    preimage = signing_preimage(g["digest"])
    assert preimage.hex() == g["preimage_hex"]
    assert len(preimage) == 71


@pytest.mark.parametrize("g", _GOLDENS["signing_preimage"], ids=lambda g: g["name"])
def test_signing_preimage_signature_parity(g, nacl):
    signing, _ = nacl
    preimage = signing_preimage(g["digest"])
    key = signing.SigningKey(bytes.fromhex(g["signer_seed_hex"]))
    assert key.verify_key.encode().hex() == g["signer_public_key_hex"]
    # Deterministic Ed25519: identical bytes to node:crypto.
    assert key.sign(preimage).signature.hex() == g["signature_hex"]
    assert _verifies(nacl, g["signer_public_key_hex"], preimage, g["signature_hex"])


@pytest.mark.parametrize("g", _GOLDENS["signing_preimage"], ids=lambda g: g["name"])
def test_raw32_signature_never_verifies_against_the_preimage(g, nacl):
    preimage = signing_preimage(g["digest"])
    raw32 = bytes.fromhex(g["digest"][len("sha256:"):])
    assert len(raw32) == 32
    assert g["raw32_signature_hex"] != g["signature_hex"]
    assert not _verifies(nacl, g["signer_public_key_hex"], preimage, g["raw32_signature_hex"])
    assert not _verifies(nacl, g["signer_public_key_hex"], raw32, g["signature_hex"])


@pytest.mark.parametrize("g", _GOLDENS["session_delegation"], ids=lambda g: g["name"])
def test_session_delegation_parity(g):
    preimage = session_key_delegation_preimage(_session_from_golden(g))
    assert preimage == g["preimage_utf8"].encode("utf-8")
    assert g["sorted_key_preimage_utf8"].encode("utf-8") != preimage


@pytest.mark.parametrize("g", _GOLDENS["session_delegation"], ids=lambda g: g["name"])
def test_session_delegation_signature_parity(g, nacl):
    signing, _ = nacl
    preimage = session_key_delegation_preimage(_session_from_golden(g))
    key = signing.SigningKey(bytes.fromhex(g["principal_seed_hex"]))
    assert key.verify_key.encode().hex() == g["principal_public_key_hex"]
    assert key.sign(preimage).signature.hex() == g["parent_signature_hex"]
    assert _verifies(nacl, g["principal_public_key_hex"], preimage, g["parent_signature_hex"])


@pytest.mark.parametrize("g", _GOLDENS["session_delegation"], ids=lambda g: g["name"])
def test_sorted_key_delegation_is_rejected(g, nacl):
    preimage = session_key_delegation_preimage(_session_from_golden(g))
    assert not _verifies(nacl, g["principal_public_key_hex"], preimage, g["sorted_key_signature_hex"])


def test_unicode_session_id_is_not_ascii_escaped():
    g = next(x for x in _GOLDENS["session_delegation"] if x["name"] == "unicode_session_id")
    text = session_key_delegation_preimage(_session_from_golden(g)).decode("utf-8")
    assert "\\u" not in text
    assert "sesión-ü-" in text


def test_derivation_path_only_when_present_and_last():
    g = next(x for x in _GOLDENS["session_delegation"] if x["name"] == "derived_session")
    text = session_key_delegation_preimage(_session_from_golden(g)).decode("utf-8")
    assert text.endswith(',"derivationPath":"m/44\'/60\'/0\'/0\'/7\'"}')
    fresh = next(x for x in _GOLDENS["session_delegation"] if x["name"] == "fresh_session")
    assert "derivationPath" not in session_key_delegation_preimage(_session_from_golden(fresh)).decode("utf-8")


def test_scope_arrays_sort_by_utf16_code_units_like_js():
    base = _session_from_golden(_GOLDENS["session_delegation"][0])
    # U+FF5E (BMP) sorts before U+1F600 (astral) by code point, but AFTER it by
    # UTF-16 code units (0xFF5E > 0xD83D). JS uses code units.
    base["scope"] = dict(base["scope"], contractIds=["\U0001F600", "～"])
    text = session_key_delegation_preimage(base).decode("utf-8")
    assert text.index("\U0001F600") < text.index("～")


@pytest.mark.parametrize("g", _GOLDENS["session_revocation"], ids=lambda g: g["name"])
def test_session_revocation_parity(g):
    preimage = session_revocation_preimage(g["revocation"])
    assert preimage == g["preimage_utf8"].encode("utf-8")


@pytest.mark.parametrize("g", _GOLDENS["session_revocation"], ids=lambda g: g["name"])
def test_session_revocation_signature_parity(g, nacl):
    preimage = session_revocation_preimage(g["revocation"])
    assert _verifies(nacl, g["principal_public_key_hex"], preimage, g["parent_signature_hex"])


class TestSurrogatesLikeJsonStringify:
    """JS strings are UTF-16 code units; Python strings are code points."""

    def _golden(self, name):
        return next(x for x in _GOLDENS["session_delegation"] if x["name"] == name)

    def test_lone_surrogates_are_escaped_not_raised(self):
        text = session_key_delegation_preimage(_session_from_golden(self._golden("lone_surrogate_strings"))).decode("utf-8")
        assert '"sessionId":"sess-\\ud800-lone"' in text
        assert '"parentAgentId":"agent-\\udfff"' in text

    def test_lone_surrogate_in_derivation_path_and_revocation(self):
        text = session_key_delegation_preimage(_session_from_golden(self._golden("surrogate_in_derivation_path"))).decode("utf-8")
        assert text.endswith(',"derivationPath":"m/\\ud800/7\'"}')
        rev = session_revocation_preimage({"sessionId": "s", "revokedAt": 1, "reason": "x\udfff"})
        assert rev == b'{"sessionId":"s","revokedAt":1,"reason":"x\\udfff"}'

    def test_two_surrogate_code_points_are_one_character_like_js(self):
        # In JS "\ud83d\ude00" IS the emoji; Python holds two code points.
        base = _session_from_golden(self._golden("fresh_session"))
        as_pair = session_key_delegation_preimage(dict(base, sessionId="\ud83d\ude00"))
        as_char = session_key_delegation_preimage(dict(base, sessionId="\U0001F600"))
        assert as_pair == as_char
        assert "\U0001F600".encode("utf-8") in as_pair

    def test_lone_surrogate_scope_entries_sort_by_code_unit(self):
        text = session_key_delegation_preimage(_session_from_golden(self._golden("lone_surrogate_strings"))).decode("utf-8")
        # UTF-16 code units: 0xD800 < 0xD83D (the emoji's high surrogate) < 0xFF5E.
        assert text.index("job-\\ud800") < text.index("job-\U0001F600") < text.index("job-\uff5e")


class TestDigestParsing:
    def test_accepts_only_the_canonical_form(self):
        assert parse_tagged_digest(DIGEST) == DIGEST
        assert is_tagged_digest(DIGEST)

    def test_raw_digest_bytes_rejected(self):
        assert _code(signing_preimage, bytes(32)) == "raw-digest-bytes"
        assert _code(signing_preimage, bytearray(32)) == "raw-digest-bytes"

    def test_trailing_newline_rejected_as_in_js(self):
        # Python's re "$" would match before "\n"; the contract (JS) does not.
        assert not is_tagged_digest(DIGEST + "\n")
        assert _code(parse_tagged_digest, DIGEST + "\n") == "malformed-tagged-digest"

    @pytest.mark.parametrize(
        "value,code",
        [
            ("0x" + DIGEST[7:], "hex-prefixed-digest"),
            ("0X" + DIGEST[7:], "hex-prefixed-digest"),
            (DIGEST[7:], "missing-sha256-tag"),
            ("SHA256:" + DIGEST[7:], "missing-sha256-tag"),
            (" " + DIGEST, "missing-sha256-tag"),
            ("sha256:" + DIGEST[7:].upper(), "malformed-tagged-digest"),
            ("sha256:" + DIGEST[8:], "malformed-tagged-digest"),
            (DIGEST + "0", "malformed-tagged-digest"),
            (None, "not-a-string"),
            (42, "not-a-string"),
        ],
    )
    def test_non_canonical_forms_rejected(self, value, code):
        assert _code(parse_tagged_digest, value) == code

    def test_registration_challenge_is_not_a_digest(self):
        assert _code(signing_preimage, "pcc-kernel-signing-key:kernel-abc") == "missing-sha256-tag"


class TestSignatureShapes:
    def test_incumbent_forms_accepted(self):
        assert len(parse_ed25519_signature_hex("ab" * 64)) == 64
        assert len(parse_ed25519_signature_hex("0x" + ("AB" * 64))) == 64
        assert parse_ed25519_public_key_hex("0X" + "cd" * 32) == bytes([0xCD]) * 32

    @pytest.mark.parametrize("value", ["ab" * 63, "ab" * 65, "zz" * 64, "", b"\x00" * 64, "0x0x" + "ab" * 62])
    def test_malformed_signatures_rejected(self, value):
        assert _code(parse_ed25519_signature_hex, value) == "malformed-signature"

    def test_malformed_public_keys_rejected(self):
        assert _code(parse_ed25519_public_key_hex, "cd" * 31) == "malformed-public-key"
        assert _code(parse_ed25519_public_key_hex, None) == "malformed-public-key"


class TestMalformedSessionKeys:
    def _base(self):
        return _session_from_golden(_GOLDENS["session_delegation"][0])

    @pytest.mark.parametrize(
        "patch",
        [
            {"publicKey": bytes(31)},
            {"publicKey": "07" * 32},
            {"expiresAt": 1.5},
            {"expiresAt": -1},
            {"issuedAt": True},  # bool is an int in Python; JSON would render true
            {"issuedAt": 2 ** 53},
            {"derivationPath": 44},
            {"derivationPath": None},
        ],
    )
    def test_rejected(self, patch):
        sk = dict(self._base(), **patch)
        assert _code(session_key_delegation_preimage, sk) == "malformed-session-key"

    def test_bad_scope_rejected(self):
        sk = self._base()
        sk["scope"] = dict(sk["scope"], contractIds=["ok", 7])
        assert _code(session_key_delegation_preimage, sk) == "malformed-session-key"
        sk["scope"] = dict(sk["scope"], contractIds=["ok"], maxSignatures=True)
        assert _code(session_key_delegation_preimage, sk) == "malformed-session-key"

    def test_malformed_revocation_rejected(self):
        assert _code(session_revocation_preimage, {"sessionId": "s", "revokedAt": 1.5, "reason": "x"}) == "malformed-revocation"
