/**
 * gen-role-tags.ts — codegen the on-chain `RoleTags.sol` library from the
 * canonical `CONTRIBUTOR_ROLES` enum + `ROLE_TAGS` keccak256 hashes that
 * live in @pcc/spec/payouts.
 *
 * Single source of truth: @pcc/spec.
 *   TS callers:   import { ROLE_TAGS } from "@pcc/spec";
 *   Solidity:     `RoleTags.OPERATOR` etc. from the file this script writes.
 *
 * Usage:
 *   pnpm --filter @pcc/contracts gen:role-tags
 *
 * Drift between the two sides is detected by:
 *   - packages/contracts/test/RoleTagsCodegen.t.sol  (forge test)
 *   - packages/contracts/ts/__tests__/payouts.test.ts (vitest)
 *
 * Both should fail on any keccak/string mismatch, gating CI.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CONTRIBUTOR_ROLES, ROLE_TAGS } from "@pcc/spec";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Convert a role string ("protocol-author") to the SCREAMING_SNAKE_CASE
 * Solidity constant name ("PROTOCOL_AUTHOR").
 */
function nameToConstant(role: string): string {
  return role.toUpperCase().replace(/-/g, "_");
}

const lines = [
  "// SPDX-License-Identifier: MIT",
  "// Code generated by packages/contracts/script/codegen/gen-role-tags.ts. DO NOT EDIT.",
  "// Single source of truth: @pcc/spec/payouts (CONTRIBUTOR_ROLES + keccak256).",
  "// Regenerate via `pnpm --filter @pcc/contracts gen:role-tags`.",
  "pragma solidity ^0.8.24;",
  "",
  "/// @title  RoleTags — canonical bytes32 keccak256 role tags for MilestoneEscrow",
  "/// @notice Mirrors the off-chain @pcc/spec ROLE_TAGS map. Drift between the two",
  "///         sides is a CI-detectable bug (RoleTagsCodegen.t.sol).",
  "/// @dev    These constants are referenced by Payout.roleTag in MilestoneEscrow.",
  "library RoleTags {",
  ...CONTRIBUTOR_ROLES.map(
    (role) =>
      `    bytes32 internal constant ${nameToConstant(role)} = ${ROLE_TAGS[role]};  // keccak256("${role}")`,
  ),
  "}",
  "",
];

const out = join(__dirname, "..", "..", "src", "RoleTags.sol");
writeFileSync(out, lines.join("\n"), "utf-8");
console.log(`gen-role-tags: wrote ${out} (${CONTRIBUTOR_ROLES.length} constants)`);
