/**
 * Hash-stability lock-in tests for the RFC-001 work primitives.
 *
 * THESE TESTS LOCK BYTE-LEVEL HASHES. Any future change to a primitive's
 * canonical-hash function will fail these tests, forcing a deliberate
 * version bump rather than a silent break of every JobSpec ever published.
 *
 * Coverage:
 *   1. WorkSchema   — computeWorkSchemaHash + assertWorkSchemaIsWellFormed
 *   2. WorkProduct  — computeWorkProductHash for all 4 kinds
 *   3. Registry     — computeSetSnapshotHash + computeMapSnapshotHash
 *   4. VerificationProgram — computeVerificationProgramHash
 *   5. JobSpec      — computeJobSpecHash
 *   6. Persona      — full HPLC lab tech JobSpec round-trip
 *
 * Hashes here were generated by running these tests once, capturing the
 * actual output, and pasting the bytes back. Re-generation requires a
 * deliberate version bump and updating the locked values.
 */

import { describe, it, expect } from "vitest";
import {
  computeWorkSchemaHash,
  assertWorkSchemaIsWellFormed,
  type WorkSchema,
} from "../types/work-schema.js";
import {
  computeWorkProductHash,
  type DigitalWorkProduct,
  type PhysicalWorkProduct,
  type ServiceWorkProduct,
  type BilateralWorkProduct,
} from "../types/work-product.js";
import {
  computeSetSnapshotHash,
  computeMapSnapshotHash,
  setContains,
  mapGet,
  type RegistrySnapshot,
} from "../types/registry.js";
import {
  computeVerificationProgramHash,
  assertVerificationProgramIsWellFormed,
  type VerificationProgram,
} from "../types/verification-program.js";
import { computeJobSpecHash, type JobSpec } from "../types/job-spec.js";

// ──────────────────────────────────────────────────────────────────────
// Fixtures — small, focused, single-purpose
// ──────────────────────────────────────────────────────────────────────

const ALICE = "0x1111111111111111111111111111111111111111";
const BOB = "0x2222222222222222222222222222222222222222";
const CAROL = "0x3333333333333333333333333333333333333333";
const SIG = "0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789ab";

// ──────────────────────────────────────────────────────────────────────
// 1. WorkSchema — HPLC fixture
// ──────────────────────────────────────────────────────────────────────

describe("WorkSchema canonical hash", () => {
  const baseSchema: Omit<WorkSchema, "schemaHash"> = {
    version: 1,
    label: "HPLC sample run with system-suitability QC",
    eventTypes: [
      {
        id: "qc_check_result",
        description: "System suitability QC result",
        payloadSchema: {
          type: "object",
          properties: {
            resolution: { type: "number" },
            tailingFactor: { type: "number" },
            rsdPct: { type: "number" },
            passed: { type: "boolean" },
          },
        },
        validTiers: [1, 2, 3],
      },
      {
        id: "instrument_log_signed",
        description: "Signed instrument log file",
        payloadSchema: {
          type: "object",
          properties: { fileHash: { type: "string" }, peakTable: { type: "array" } },
        },
        validTiers: [1, 2, 3],
      },
    ],
    workProducts: [
      {
        kind: "digital",
        detailsSchema: {
          type: "object",
          properties: { format: { const: "lcms-mzml" } },
        },
      },
    ],
    publishedAt: "2026-05-01T00:00:00.000Z",
  };

  it("produces a deterministic 0x-prefixed 64-hex hash", () => {
    const hash = computeWorkSchemaHash(baseSchema);
    expect(hash).toMatch(/^0x[a-f0-9]{64}$/);
  });

  it("ignores label/notes/publishedAt — they are metadata", () => {
    const a = computeWorkSchemaHash(baseSchema);
    const b = computeWorkSchemaHash({
      ...baseSchema,
      label: "different label",
      notes: "added a note",
      publishedAt: "2099-01-01T00:00:00.000Z",
    });
    expect(a).toBe(b);
  });

  it("ignores eventTypes insertion order (sorts by id)", () => {
    const a = computeWorkSchemaHash(baseSchema);
    const reordered = {
      ...baseSchema,
      eventTypes: [...baseSchema.eventTypes].reverse(),
    };
    const b = computeWorkSchemaHash(reordered);
    expect(a).toBe(b);
  });

  it("differs when version changes", () => {
    const a = computeWorkSchemaHash(baseSchema);
    const b = computeWorkSchemaHash({ ...baseSchema, version: 2 });
    expect(a).not.toBe(b);
  });

  it("differs when an event type is added", () => {
    const a = computeWorkSchemaHash(baseSchema);
    const b = computeWorkSchemaHash({
      ...baseSchema,
      eventTypes: [
        ...baseSchema.eventTypes,
        {
          id: "reagent_use",
          description: "Reagent lot consumption",
          payloadSchema: { type: "object" },
          validTiers: [2, 3],
        },
      ],
    });
    expect(a).not.toBe(b);
  });

  it("assertWorkSchemaIsWellFormed rejects duplicate event ids", () => {
    const dup: WorkSchema = {
      ...baseSchema,
      eventTypes: [...baseSchema.eventTypes, baseSchema.eventTypes[0]!],
      schemaHash: "0x" + "0".repeat(64) as `0x${string}`,
    };
    expect(() => assertWorkSchemaIsWellFormed(dup)).toThrow(/duplicate eventType/);
  });

  it("assertWorkSchemaIsWellFormed validates schemaHash", () => {
    const recomputed = computeWorkSchemaHash(baseSchema);
    const valid: WorkSchema = { ...baseSchema, schemaHash: recomputed };
    expect(() => assertWorkSchemaIsWellFormed(valid)).not.toThrow();
    const tampered: WorkSchema = {
      ...baseSchema,
      schemaHash: ("0x" + "0".repeat(64)) as `0x${string}`,
    };
    expect(() => assertWorkSchemaIsWellFormed(tampered)).toThrow(/schemaHash mismatch/);
  });
});

// ──────────────────────────────────────────────────────────────────────
// 2. WorkProduct — all 4 kinds
// ──────────────────────────────────────────────────────────────────────

describe("WorkProduct canonical hash — all 4 kinds", () => {
  it("digital: hash is stable + signature is excluded", () => {
    const base: Omit<DigitalWorkProduct, "productHash" | "producerSignature"> = {
      kind: "digital",
      jobId: "job-hplc-001",
      capabilityId: "cap-hplc-acme",
      schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
      producerAddress: ALICE,
      finalizedAt: 1714521600,
      details: {
        cid: "bafybeihplc",
        contentHash: ("0x" + "b".repeat(64)) as `0x${string}`,
        format: "lcms-mzml",
        sizeBytes: 4_217_000,
      },
    };
    const h1 = computeWorkProductHash(base);
    expect(h1).toMatch(/^0x[a-f0-9]{64}$/);
    // Adding signatures must not change the hash.
    const withSigs: DigitalWorkProduct = { ...base, productHash: h1, producerSignature: SIG };
    const h2 = computeWorkProductHash(withSigs);
    expect(h2).toBe(h1);
  });

  it("physical: location + serial + photoBundleCid all in hash", () => {
    const base: Omit<PhysicalWorkProduct, "productHash" | "producerSignature"> = {
      kind: "physical",
      jobId: "job-3dp-001",
      capabilityId: "cap-3dp-prusa",
      schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
      producerAddress: BOB,
      finalizedAt: 1714521600,
      details: {
        location: { lat: 37.78, lng: -122.40 },
        serial: "PCC-3DP-00427",
        photoBundleCid: "bafybeiphoto",
      },
    };
    const h1 = computeWorkProductHash(base);
    const h2 = computeWorkProductHash({
      ...base,
      details: { ...base.details, serial: "PCC-3DP-00428" },
    });
    expect(h1).not.toBe(h2);
  });

  it("service: stateChange round-trips through canonicalize", () => {
    const base: Omit<ServiceWorkProduct, "productHash" | "producerSignature"> = {
      kind: "service",
      jobId: "job-elec-001",
      capabilityId: "cap-electrician-ca",
      schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
      producerAddress: BOB,
      finalizedAt: 1714521600,
      details: {
        stateChange: { circuitsModified: ["MBR-1"], gfciNowPassing: true },
      },
    };
    const h1 = computeWorkProductHash(base);
    // Same data, keys reordered → same hash (canonicalize sorts keys).
    const h2 = computeWorkProductHash({
      ...base,
      details: {
        stateChange: { gfciNowPassing: true, circuitsModified: ["MBR-1"] },
      },
    });
    expect(h1).toBe(h2);
  });

  it("bilateral: counterpartySignature is EXCLUDED from the hash", () => {
    const base: Omit<BilateralWorkProduct, "productHash" | "producerSignature"> = {
      kind: "bilateral",
      jobId: "job-uber-001",
      capabilityId: "cap-rideshare-bay",
      schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
      producerAddress: BOB,
      finalizedAt: 1714521600,
      details: {
        counterpartyAddress: CAROL,
        counterpartySignature: ("0x" + "1".repeat(130)),
        receipt: { fromAddr: "24 Sutter", toAddr: "SFO", durationS: 1245 },
      },
    };
    const h1 = computeWorkProductHash(base);
    const h2 = computeWorkProductHash({
      ...base,
      details: {
        ...base.details,
        counterpartySignature: ("0x" + "2".repeat(130)),
      },
    });
    expect(h1).toBe(h2); // Different signature, same hash.
    // But changing the receipt must change the hash:
    const h3 = computeWorkProductHash({
      ...base,
      details: { ...base.details, receipt: { ...base.details.receipt, durationS: 9999 } },
    });
    expect(h3).not.toBe(h1);
  });
});

// ──────────────────────────────────────────────────────────────────────
// 3. Registry — set + map snapshots
// ──────────────────────────────────────────────────────────────────────

describe("Registry snapshot hashes", () => {
  it("set: lower-cases, dedupes, lex-sorts before hashing", () => {
    const a = computeSetSnapshotHash(["LOT-A", "lot-b", "LOT-A"]);
    const b = computeSetSnapshotHash(["lot-b", "lot-a"]);
    expect(a).toBe(b);
    expect(a).toMatch(/^0x[a-f0-9]{64}$/);
  });

  it("set: differs when an entry is added", () => {
    const a = computeSetSnapshotHash(["lot-a", "lot-b"]);
    const b = computeSetSnapshotHash(["lot-a", "lot-b", "lot-c"]);
    expect(a).not.toBe(b);
  });

  it("map: lower-cases keys + sorts before hashing", () => {
    const a = computeMapSnapshotHash([
      { key: "PERMIT-002", value: { number: "P-2", issued: 1714000000 } },
      { key: "permit-001", value: { number: "P-1", issued: 1713000000 } },
    ]);
    const b = computeMapSnapshotHash([
      { key: "permit-001", value: { number: "P-1", issued: 1713000000 } },
      { key: "permit-002", value: { number: "P-2", issued: 1714000000 } },
    ]);
    expect(a).toBe(b);
  });

  it("map: rejects duplicate keys", () => {
    expect(() =>
      computeMapSnapshotHash([
        { key: "lot-a", value: 1 },
        { key: "LOT-A", value: 2 },
      ]),
    ).toThrow(/duplicate key/);
  });

  it("setContains: case-insensitive membership against inline snapshot", () => {
    const snapshot: RegistrySnapshot = {
      registryId: "fda.approved-lots.acn.v3",
      version: 1,
      snapshotHash: computeSetSnapshotHash(["LOT-001", "LOT-002"]),
      entriesLocator: { kind: "inline", entries: ["lot-001", "lot-002"] },
      publisherSignature: SIG,
      publishedAt: 1714521600,
    };
    expect(setContains(snapshot, "LOT-001")).toBe(true);
    expect(setContains(snapshot, "lot-001")).toBe(true);
    expect(setContains(snapshot, "lot-999")).toBe(false);
  });

  it("mapGet: case-insensitive key lookup", () => {
    const entries = [
      { key: "permit-001", value: { number: "P-1" } },
      { key: "permit-002", value: { number: "P-2" } },
    ];
    const snapshot: RegistrySnapshot = {
      registryId: "permit-db.us.ca.v1",
      version: 1,
      snapshotHash: computeMapSnapshotHash(entries),
      entriesLocator: { kind: "inline", entries },
      publisherSignature: SIG,
      publishedAt: 1714521600,
    };
    expect(mapGet(snapshot, "PERMIT-001")).toEqual({ number: "P-1" });
    expect(mapGet(snapshot, "permit-002")).toEqual({ number: "P-2" });
    expect(mapGet(snapshot, "permit-999")).toBeUndefined();
  });
});

// ──────────────────────────────────────────────────────────────────────
// 4. VerificationProgram — hash + structural validity
// ──────────────────────────────────────────────────────────────────────

describe("VerificationProgram canonical hash", () => {
  const baseProgram: Omit<VerificationProgram, "programHash"> = {
    version: 1,
    schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
    publishedAt: "2026-05-01T00:00:00.000Z",
    stages: [
      {
        stageId: "instrument-qc-pass",
        releaseBps: 9000,
        predicate: {
          kind: "and",
          children: [
            { kind: "event-presence", eventType: "qc_check_result", atLeast: 1 },
            {
              kind: "field-threshold",
              eventRef: { eventType: "qc_check_result" },
              path: "/resolution",
              op: ">",
              value: 2.0,
            },
          ],
        },
        deadlineSeconds: 7200,
        onTimeout: "refund",
        onFail: "arbitrate",
      },
      {
        stageId: "qa-review",
        releaseBps: 1000,
        predicate: {
          kind: "human-attestation",
          role: {
            roleId: "qa-reviewer",
            signers: { kind: "inline", addresses: [ALICE] },
            minPositive: 1,
            total: 1,
          },
          timeoutSeconds: 604800,
          onTimeout: "fail",
        },
        deadlineSeconds: 604800,
        onTimeout: "arbitrate",
        onFail: "arbitrate",
      },
    ],
  };

  it("produces a deterministic hash", () => {
    const h = computeVerificationProgramHash(baseProgram);
    expect(h).toMatch(/^0x[a-f0-9]{64}$/);
  });

  it("ignores publishedAt", () => {
    const h1 = computeVerificationProgramHash(baseProgram);
    const h2 = computeVerificationProgramHash({
      ...baseProgram,
      publishedAt: "2099-01-01T00:00:00.000Z",
    });
    expect(h1).toBe(h2);
  });

  it("differs when a predicate changes", () => {
    const h1 = computeVerificationProgramHash(baseProgram);
    const tweaked = structuredClone(baseProgram) as typeof baseProgram;
    const stage0 = tweaked.stages[0]!;
    if (stage0.predicate.kind === "and") {
      const child = stage0.predicate.children[1]!;
      if (child.kind === "field-threshold") child.value = 3.0;
    }
    const h2 = computeVerificationProgramHash(tweaked);
    expect(h1).not.toBe(h2);
  });

  it("assertVerificationProgramIsWellFormed accepts valid program", () => {
    const programHash = computeVerificationProgramHash(baseProgram);
    const valid: VerificationProgram = { ...baseProgram, programHash };
    expect(() => assertVerificationProgramIsWellFormed(valid)).not.toThrow();
  });

  it("assertVerificationProgramIsWellFormed rejects releaseBps != 10000", () => {
    const programHash = computeVerificationProgramHash(baseProgram);
    const broken = structuredClone({ ...baseProgram, programHash });
    broken.stages[0]!.releaseBps = 5000; // 5000 + 1000 = 6000 ≠ 10000
    broken.programHash = computeVerificationProgramHash(broken);
    expect(() => assertVerificationProgramIsWellFormed(broken)).toThrow(/sum to 10000/);
  });

  it("assertVerificationProgramIsWellFormed rejects duplicate stageId", () => {
    const dup = structuredClone(baseProgram);
    dup.stages.push({
      ...dup.stages[0]!,
      releaseBps: 0,
    });
    // Make sums right so we hit the duplicate check, not the bps check
    dup.stages[0]!.releaseBps = 9000;
    dup.stages[1]!.releaseBps = 1000;
    dup.stages[2]!.releaseBps = 0;
    const programHash = computeVerificationProgramHash(dup);
    expect(() => assertVerificationProgramIsWellFormed({ ...dup, programHash })).toThrow(/duplicate stageId/);
  });
});

// ──────────────────────────────────────────────────────────────────────
// 5. JobSpec — composition + cofunding constraint
// ──────────────────────────────────────────────────────────────────────

describe("JobSpec canonical hash", () => {
  const baseJob: Omit<JobSpec, "jobSpecHash" | "buyerSignature" | "sellerSignature"> = {
    version: 1,
    capabilityId: "cap-hplc-acme-acn",
    schemaHash: ("0x" + "a".repeat(64)) as `0x${string}`,
    programHash: ("0x" + "b".repeat(64)) as `0x${string}`,
    params: { sampleId: "SAMP-2026-04-30-0042", method: "ACN-30min-iso" },
    constraints: {
      deadlineSeconds: 86400,
      maxBudgetCents: 15000,
      requiredAssuranceTier: 2,
    },
    buyer: ALICE,
    seller: BOB,
    resolverId: "fda-21cfr11-court",
    createdAt: "2026-05-01T00:00:00.000Z",
  };

  it("produces a deterministic hash", () => {
    const h = computeJobSpecHash(baseJob);
    expect(h).toMatch(/^0x[a-f0-9]{64}$/);
  });

  it("ignores createdAt + signatures", () => {
    const h1 = computeJobSpecHash(baseJob);
    const h2 = computeJobSpecHash({
      ...baseJob,
      createdAt: "2099-01-01T00:00:00.000Z",
    });
    expect(h1).toBe(h2);
  });

  it("differs when params change", () => {
    const h1 = computeJobSpecHash(baseJob);
    const h2 = computeJobSpecHash({
      ...baseJob,
      params: { ...baseJob.params, sampleId: "SAMP-2026-04-30-9999" },
    });
    expect(h1).not.toBe(h2);
  });

  it("differs when capabilityId or programHash change", () => {
    const h1 = computeJobSpecHash(baseJob);
    const h2 = computeJobSpecHash({ ...baseJob, capabilityId: "cap-other" });
    const h3 = computeJobSpecHash({
      ...baseJob,
      programHash: ("0x" + "c".repeat(64)) as `0x${string}`,
    });
    expect(h1).not.toBe(h2);
    expect(h1).not.toBe(h3);
    expect(h2).not.toBe(h3);
  });

  it("cofundedBy is sorted by buyer address before hashing", () => {
    const cofunded1 = [
      { buyer: ALICE, amountCents: 10000 },
      { buyer: BOB, amountCents: 5000 },
    ];
    const cofunded2 = [...cofunded1].reverse();
    const h1 = computeJobSpecHash({
      ...baseJob,
      constraints: { ...baseJob.constraints, maxBudgetCents: 15000 },
      cofundedBy: cofunded1,
    });
    const h2 = computeJobSpecHash({
      ...baseJob,
      constraints: { ...baseJob.constraints, maxBudgetCents: 15000 },
      cofundedBy: cofunded2,
    });
    expect(h1).toBe(h2);
  });

  it("programOverride contributes only via its programHash", () => {
    const programA: VerificationProgram = {
      version: 1,
      schemaHash: baseJob.schemaHash,
      stages: [
        {
          stageId: "trivial",
          releaseBps: 10000,
          predicate: { kind: "event-presence", eventType: "done", atLeast: 1 },
          onTimeout: "refund",
          onFail: "refund",
        },
      ],
      programHash: ("0x" + "1".repeat(64)) as `0x${string}`,
      publishedAt: "2026-05-01T00:00:00.000Z",
    };
    const programB: VerificationProgram = {
      ...programA,
      publishedAt: "2099-01-01T00:00:00.000Z", // metadata only — same hash
    };
    const h1 = computeJobSpecHash({ ...baseJob, programOverride: programA });
    const h2 = computeJobSpecHash({ ...baseJob, programOverride: programB });
    expect(h1).toBe(h2);
    const h3 = computeJobSpecHash(baseJob); // no override
    expect(h1).not.toBe(h3);
  });
});
