#!/usr/bin/env python3
"""
Independent stdlib cross-check of finalmilestonepackage-v2-d1-eip712.vectors.json (D1 operator
EIP-712 signature of FinalMilestonePackageV2 -- returns/pcc-evidence-work/d1-eip712-struct-proposal.md,
RATIFIED by the oracle (bus #5773) and escrow (bus #5785), 2026-10-03). Public test data tooling.

Standard library ONLY: hashlib, json, os, sys. It does NOT import the sibling .cjs generator, ethers,
or any third-party crypto library -- it re-derives everything from the JSON ONLY, using its own
from-scratch Keccak-256 and secp256k1 implementations, independently of the JS/ethers that produced
the vectors (the same relationship oracle-verdict-content-v2.vectors.py has to its sibling .json).

Two things this file embeds from scratch, because the standard library cannot do them:

  1. Keccak-256 (Keccak-f[1600], rate 136 bytes, original Keccak pad10*1 with domain suffix 0x01).
     hashlib.sha3_256 is NOT this -- NIST's FIPS 202 changed the padding suffix (0x06) when it
     standardized Keccak as SHA-3, so hashlib's sha3_256 produces DIFFERENT output than Ethereum's
     keccak256 for the same input. Self-tested against the known vector keccak256(b"") ==
     c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 (asserted at import time).
     Rotation offsets are generated by the spec's own recurrence (FIPS 202 sec 3.2.2), not transcribed
     from a flat table, to avoid a silent transposition error; round constants are the standard
     Keccak-f[1600] table.

  2. secp256k1 point arithmetic (affine, double-and-add, Fermat-inverse via pow(a, p-2, p) since both
     the field prime and the curve order are prime) and ECDSA public-key recovery from (digest, r, s,
     v), used to independently recover a signer address from each vector's signature.

From the JSON alone, this script recomputes:
  * typeHash -- from a FIELDS list matching the contract's exact struct declaration, independent of
    the JSON's own stored typeString (both are compared).
  * domainSeparator -- hashStruct("EIP712Domain(string name,string version,uint256 chainId,address
    verifyingContract)", domain), for every vector's own domain object (not just the canonical one).
  * structHash and digest -- for every vector's own domain + message.
  * the recovered address of every vector, applying the SAME accept/refuse gate the JS mirror
    implements (length == 65 bytes, 0 < r < n, 0 < s <= n/2 low-s, v in {27,28}, non-zero recovered
    address, recovered == authoritative operator, operatorPrincipalId byte-exact lowercase match,
    signer label match) -- with the SAME reason codes, so each vector's `expected.reason` and the
    JSON's own stored `result` (what the JS mirror computed) are both independently reproduced here.

packageBodyHash is the ONE value this script does NOT re-derive from first principles, and says so
explicitly below: its framing (SHA-256(raw32(SIG_DOMAIN) || u64be(len(JCS)) || JCS)) depends on the
production SIG_DOMAIN constant and the JCS canonicalization algorithm, which are properties of the
signing pipeline (packages/spec canonicalize + finalmilestonepackage-v2-preview-mirror.cjs), not of
this EIP-712-specific vectors file, and are not themselves carried as JSON data here (only the
resulting body object and hash are). Its correctness against finalmilestonepackage-v2-preview-
mirror.cjs's own independently-pinned EXPECT.packageBodyHash was already cross-checked by the JS
generator (sampleBody.packageBodyHashMatchesPreviewMirror); this script re-asserts that recorded
fact and uses the JSON's packageBodyHash value as an ordinary (trusted) bytes32 struct field input
for every structHash/digest recomputation -- exactly as the real D1 verifier would receive it from
the package envelope, having already checked it elsewhere.

Exit status 0 only if every check passes.
"""
import hashlib  # noqa: F401 (imported per the brief's allowed stdlib set; not used -- keccak256 is hand-rolled, see module docstring)
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VECTOR = os.path.join(HERE, "finalmilestonepackage-v2-d1-eip712.vectors.json")

# ─────────────────────────────── Keccak-256 (pure Python, stdlib only) ───────────────────────────────
_MASK64 = (1 << 64) - 1


def _rotl64(x, n):
    n %= 64
    if n == 0:
        return x & _MASK64
    return ((x << n) | (x >> (64 - n))) & _MASK64


def _build_rho_offsets():
    """FIPS 202 sec 3.2.2 Algorithm 2 (rho offset generation), not a transcribed flat table."""
    off = [[0] * 5 for _ in range(5)]  # off[x][y]
    x, y = 1, 0
    for t in range(24):
        off[x][y] = ((t + 1) * (t + 2) // 2) % 64
        x, y = y, (2 * x + 3 * y) % 5
    return off


_RHO = _build_rho_offsets()
_RC = [
    0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
    0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
    0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
    0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
    0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
    0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
]


def _keccak_f1600(lanes):
    """lanes: 25 ints (64-bit each), lanes[x + 5*y], mutated in place."""
    for rnd in range(24):
        c = [lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20] for x in range(5)]
        d = [c[(x - 1) % 5] ^ _rotl64(c[(x + 1) % 5], 1) for x in range(5)]
        for x in range(5):
            for y in range(5):
                lanes[x + 5 * y] ^= d[x]
        b = [0] * 25
        for x in range(5):
            for y in range(5):
                nx, ny = y, (2 * x + 3 * y) % 5
                b[nx + 5 * ny] = _rotl64(lanes[x + 5 * y], _RHO[x][y])
        for x in range(5):
            for y in range(5):
                lanes[x + 5 * y] = b[x + 5 * y] ^ ((~b[((x + 1) % 5) + 5 * y]) & b[((x + 2) % 5) + 5 * y] & _MASK64)
        lanes[0] ^= _RC[rnd]
    return lanes


def keccak256(data: bytes) -> bytes:
    rate = 136  # bytes; Keccak-256 capacity=512 bits=64 bytes, state=200 bytes, rate=200-64=136
    msg = bytearray(data)
    msg.append(0x01)  # original Keccak pad10*1 domain suffix (NOT NIST SHA3's 0x06 -- THE gotcha)
    while len(msg) % rate != 0:
        msg.append(0x00)
    msg[-1] ^= 0x80
    lanes = [0] * 25
    for block_start in range(0, len(msg), rate):
        block = msg[block_start:block_start + rate]
        for i in range(rate // 8):
            lanes[i] ^= int.from_bytes(block[8 * i:8 * i + 8], "little")
        _keccak_f1600(lanes)
    out = b""
    for i in range(4):  # squeeze 32 bytes = 4 lanes
        out += lanes[i].to_bytes(8, "little")
    return out


_KECCAK_EMPTY_EXPECTED = "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
assert keccak256(b"").hex() == _KECCAK_EMPTY_EXPECTED, "Keccak-256 self-test FAILED: keccak256(b'') mismatch"

# ─────────────────────────────── secp256k1 (pure Python, stdlib only) ────────────────────────────────
_P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
_N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
_GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
_GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
_A = 0
_B = 7
_G = (_GX, _GY)
SECP256K1_N = _N
SECP256K1_N2 = _N // 2  # floor(n/2)
_HOUSE_N2_LITERAL = 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0  # finalmilestonepackage-sig-golden-vector.cjs
assert SECP256K1_N2 == _HOUSE_N2_LITERAL, "secp256k1 n/2 does not match the house constant"


def _inv_mod(a, m):
    return pow(a, m - 2, m)  # Fermat's little theorem; both _P and _N are prime


def _point_add(p1, p2):
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    x1, y1 = p1
    x2, y2 = p2
    if x1 == x2:
        if (y1 + y2) % _P == 0:
            return None
        lam = ((3 * x1 * x1 + _A) * _inv_mod((2 * y1) % _P, _P)) % _P
    else:
        lam = ((y2 - y1) * _inv_mod((x2 - x1) % _P, _P)) % _P
    x3 = (lam * lam - x1 - x2) % _P
    y3 = (lam * (x1 - x3) - y1) % _P
    return (x3, y3)


def _scalar_mult(k, pt):
    result = None
    addend = pt
    while k:
        if k & 1:
            result = _point_add(result, addend)
        addend = _point_add(addend, addend)
        k >>= 1
    return result


def _on_curve(pt):
    if pt is None:
        return True
    x, y = pt
    return (y * y - (x * x * x + _A * x + _B)) % _P == 0


def _mod_sqrt(a, p):
    r = pow(a, (p + 1) // 4, p)  # valid since p % 4 == 3 for secp256k1's field prime
    if (r * r) % p != a % p:
        return None
    return r


assert _on_curve(_G), "generator point G is not on curve -- constants are wrong"


def ecrecover(digest_bytes: bytes, r: int, s: int, v: int):
    """Unconstrained ECDSA public-key recovery (affine point, (x,y)). Range/canonical-form policy is
    the CALLER's job (see verify_d1 below) -- this function will recover from ANY mathematically
    valid (r, s, v), including non-canonical high-s, which is deliberate: it is what lets the
    informational high-s malleability check (main(), below) demonstrate the malleable twin recovers
    the same address, something ethers.recoverAddress itself refuses to compute (see the high-s
    vector's `note` in the JSON)."""
    recid = v - 27
    if not (0 <= recid <= 1):
        raise ValueError("recid out of range (v must be 27 or 28)")
    if not (0 < r < _N):
        raise ValueError("r out of range")
    if not (0 < s < _N):
        raise ValueError("s out of range")
    x = r
    if x >= _P:
        raise ValueError("r as x-coordinate exceeds field prime")
    rhs = (x * x * x + _A * x + _B) % _P
    y = _mod_sqrt(rhs, _P)
    if y is None:
        raise ValueError("invalid point: r does not correspond to a curve point")
    if (y % 2) != (recid & 1):
        y = _P - y
    r_point = (x, y)
    if not _on_curve(r_point):
        raise ValueError("decompressed R not on curve")
    e = int.from_bytes(digest_bytes, "big") % _N
    r_inv = _inv_mod(r, _N)
    u1 = (-e * r_inv) % _N
    u2 = (s * r_inv) % _N
    q = _point_add(_scalar_mult(u1, _G), _scalar_mult(u2, r_point))
    if q is None:
        raise ValueError("recovered point at infinity")
    return q


def address_from_point(point) -> str:
    x, y = point
    pub = x.to_bytes(32, "big") + y.to_bytes(32, "big")
    h = keccak256(pub)
    return "0x" + h[-20:].hex()


# ─────────────────────────────── EIP-712 encoding (FinalMilestonePackageV2) ──────────────────────────
FIELDS = [
    ("chainId", "uint256"),
    ("escrow", "address"),
    ("settlementUnitId", "bytes32"),
    ("jobIdHash", "bytes32"),
    ("milestoneIndex", "uint256"),
    ("stepId", "bytes32"),
    ("compositionRoot", "bytes32"),
    ("acceptedEnvelopeHash", "bytes32"),
    ("packageBodyHash", "bytes32"),
]
TYPE_STRING = "FinalMilestonePackageV2(" + ",".join(f"{t} {n}" for n, t in FIELDS) + ")"
TYPE_HASH = keccak256(TYPE_STRING.encode("utf-8"))
DOMAIN_TYPE_HASH = keccak256(b"EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)")


def _enc_uint256(value) -> bytes:
    return int(value).to_bytes(32, "big")


def _enc_address(addr_hex: str) -> bytes:
    h = addr_hex[2:] if addr_hex.startswith("0x") else addr_hex
    b = bytes.fromhex(h)
    assert len(b) == 20, f"address must be 20 bytes, got {len(b)}"
    return b.rjust(32, b"\x00")


def _enc_bytes32(hex32: str) -> bytes:
    h = hex32[2:] if hex32.startswith("0x") else hex32
    b = bytes.fromhex(h)
    assert len(b) == 32, f"bytes32 must be 32 bytes, got {len(b)}"
    return b


def _enc_string_hashed(s: str) -> bytes:
    return keccak256(s.encode("utf-8"))


def _encode_field(ftype: str, value) -> bytes:
    if ftype == "uint256":
        return _enc_uint256(value)
    if ftype == "address":
        return _enc_address(value)
    if ftype == "bytes32":
        return _enc_bytes32(value)
    raise ValueError(f"unsupported field type {ftype}")


def hash_struct(message: dict) -> bytes:
    parts = [TYPE_HASH]
    for name, ftype in FIELDS:
        parts.append(_encode_field(ftype, message[name]))
    return keccak256(b"".join(parts))


def hash_domain(domain: dict) -> bytes:
    parts = [
        DOMAIN_TYPE_HASH,
        _enc_string_hashed(domain["name"]),
        _enc_string_hashed(domain["version"]),
        _enc_uint256(domain["chainId"]),
        _enc_address(domain["verifyingContract"]),
    ]
    return keccak256(b"".join(parts))


def eip712_digest(domain: dict, message: dict):
    ds = hash_domain(domain)
    sh = hash_struct(message)
    dg = keccak256(b"\x19\x01" + ds + sh)
    return dg, ds, sh


# ─────────────────────────────── D1 verifier (mirrors the JS mirror's gates exactly) ─────────────────
_ZERO_ADDRESS = "0x" + "00" * 20


def verify_d1(digest_bytes: bytes, sig_hex: str, expected_operator: str) -> dict:
    hexstr = (sig_hex[2:] if sig_hex.startswith("0x") else sig_hex).lower()
    if len(hexstr) != 130:
        return {"accepted": False, "reason": "bad_length", "recovered": None}
    r = int(hexstr[0:64], 16)
    s = int(hexstr[64:128], 16)
    v = int(hexstr[128:130], 16)
    if r == 0:
        return {"accepted": False, "reason": "r_zero", "recovered": None}
    if r >= SECP256K1_N:
        return {"accepted": False, "reason": "r_out_of_range", "recovered": None}
    if s == 0:
        return {"accepted": False, "reason": "s_zero", "recovered": None}
    if s >= SECP256K1_N:
        return {"accepted": False, "reason": "s_out_of_range", "recovered": None}
    if v != 27 and v != 28:
        return {"accepted": False, "reason": "v_not_27_or_28", "recovered": None}
    if s > SECP256K1_N2:
        return {"accepted": False, "reason": "high_s", "recovered": None}
    try:
        q = ecrecover(digest_bytes, r, s, v)
        recovered = address_from_point(q)
    except Exception as e:  # noqa: BLE001 -- deliberately broad: any recovery failure is a refusal, not a crash
        return {"accepted": False, "reason": "recovery_exception", "recovered": None, "detail": str(e)}
    if recovered.lower() == _ZERO_ADDRESS:
        return {"accepted": False, "reason": "zero_address", "recovered": recovered}
    if recovered.lower() != expected_operator.lower():
        return {"accepted": False, "reason": "signer_mismatch", "recovered": recovered}
    return {"accepted": True, "reason": None, "recovered": recovered}


def _is_valid_operator_principal_id_shape(s: str) -> bool:
    """^eip155:[0-9]+:0x[0-9a-f]{40}$ without `re` (not in the brief's allowed stdlib set)."""
    prefix = "eip155:"
    if not s.startswith(prefix):
        return False
    rest = s[len(prefix):]
    parts = rest.split(":")
    if len(parts) != 2:
        return False
    chain_part, addr_part = parts
    if len(chain_part) == 0 or not all(c in "0123456789" for c in chain_part):
        return False
    if not addr_part.startswith("0x"):
        return False
    hexpart = addr_part[2:]
    if len(hexpart) != 40:
        return False
    if not all(c in "0123456789abcdef" for c in hexpart):
        return False
    return True


def check_operator_principal_id(claimed: str, chain_id_decimal_str: str, recovered_addr: str) -> dict:
    if not _is_valid_operator_principal_id_shape(claimed):
        return {"ok": False, "reason": "operatorPrincipalId_not_lowercase"}
    canon = f"eip155:{chain_id_decimal_str}:{recovered_addr.lower()}"
    if claimed != canon:
        return {"ok": False, "reason": "operatorPrincipalId_mismatch"}
    return {"ok": True}


def verify_d1_entry(digest_bytes, sig_hex, expected_operator, claimed_operator_principal_id, claimed_signer_label, chain_id_decimal_str) -> dict:
    sig_check = verify_d1(digest_bytes, sig_hex, expected_operator)
    if not sig_check["accepted"]:
        return sig_check
    pc = check_operator_principal_id(claimed_operator_principal_id, chain_id_decimal_str, sig_check["recovered"])
    if not pc["ok"]:
        return {"accepted": False, "reason": pc["reason"], "recovered": sig_check["recovered"]}
    if claimed_signer_label.lower() != sig_check["recovered"].lower():
        return {"accepted": False, "reason": "signer_label_mismatch", "recovered": sig_check["recovered"]}
    return {"accepted": True, "reason": None, "recovered": sig_check["recovered"]}


# ─────────────────────────────────────────────── main ────────────────────────────────────────────────
failures = []


def check(label, ok, detail=""):
    print(("  ok   " if ok else "  FAIL ") + label + ("" if ok else f"  {detail}"))
    if not ok:
        failures.append(label)


def main():
    v = json.load(open(VECTOR, encoding="utf-8"))

    print(f"Keccak-256 self-test: keccak256(b'') == {_KECCAK_EMPTY_EXPECTED} (asserted at import time)")
    print(f"secp256k1 n/2 == house constant (asserted at import time): 0x{SECP256K1_N2:x}")
    print()

    print("typeHash / domainSeparator (recomputed from the FIELDS list + domain object, not copied)")
    check("typeString (built from FIELDS) matches stored", TYPE_STRING == v["typeString"], TYPE_STRING)
    got_type_hash = "0x" + TYPE_HASH.hex()
    check("typeHash matches stored", got_type_hash == v["typeHash"], got_type_hash)
    ds_canonical = hash_domain(v["domain"])
    got_ds_canonical = "0x" + ds_canonical.hex()
    check("domainSeparator (canonical domain) matches stored", got_ds_canonical == v["domainSeparator"], got_ds_canonical)
    print()

    print("packageBodyHash: TRUSTED from the JSON, not re-derived from the raw body (see module docstring")
    print("for why -- the framing needs the production SIG_DOMAIN constant + JCS algorithm, which are not")
    print("carried as JSON data here). Re-asserting the JS generator's own recorded cross-check instead:")
    check("sampleBody.packageBodyHashMatchesPreviewMirror is recorded true (JS-side cross-check against finalmilestonepackage-v2-preview-mirror.cjs)",
          v["sampleBody"]["packageBodyHashMatchesPreviewMirror"] is True)
    check("positive.message.packageBodyHash == sampleBody.packageBodyHash (internally consistent)",
          v["positive"]["message"]["packageBodyHash"] == v["sampleBody"]["packageBodyHash"])
    print()

    operator_addr = v["keys"]["operator"]["address"]
    non_operator_addr = v["keys"]["nonOperator"]["address"]

    print("POSITIVE vector")
    pos = v["positive"]
    digest_bytes, ds_pos, sh_pos = eip712_digest(v["domain"], pos["message"])
    got_digest = "0x" + digest_bytes.hex()
    got_struct_hash = "0x" + sh_pos.hex()
    check("positive structHash matches stored", got_struct_hash == pos["structHash"], got_struct_hash)
    check("positive digest matches stored", got_digest == pos["digest"], got_digest)
    result = verify_d1_entry(digest_bytes, pos["signature"]["full"], operator_addr, pos["operatorPrincipalId"], pos["signerLabel"], v["domain"]["chainId"])
    check("positive: accepted == True", result["accepted"] is True, json.dumps(result))
    check("positive: recovered == operator", bool(result["recovered"]) and result["recovered"].lower() == operator_addr.lower(), result.get("recovered"))
    check("positive: Python's independent result matches the JSON's own stored result (JS/Python agree)",
          result["accepted"] == pos["result"]["accepted"] and result["reason"] == pos["result"]["reason"], json.dumps(result))
    print()

    print(f"NEGATIVES ({len(v['negatives'])} vectors): each vector's OWN domain+message re-hashed, its")
    print("signature independently re-verified under the same accept/refuse gate as the JS mirror.")
    for neg in v["negatives"]:
        name = neg["name"]
        dg_bytes, _, _ = eip712_digest(neg["domain"], neg["message"])
        got_dg = "0x" + dg_bytes.hex()
        check(f"{name}: digest recomputed from its own domain+message matches stored", got_dg == neg["digest"], got_dg)
        # claimed_signer_label: the JS generator used operatorWallet.address uniformly for every
        # negative (verified by reading finalmilestonepackage-v2-d1-eip712-mirror.cjs -- csl is never
        # overridden in any of the 15 pushNeg/manual negative constructions). It is not itself stored
        # per-negative in the JSON. This is safe to replicate here because in every one of the 15
        # negatives the signature-rule or operatorPrincipalId check already refuses BEFORE the signer-
        # label gate would ever be reached (confirmed per-vector by the reason codes below, none of
        # which is signer_label_mismatch) -- so this placeholder cannot be the thing that makes a
        # check pass or fail.
        res = verify_d1_entry(dg_bytes, neg["signature"]["full"], operator_addr, neg["claimedOperatorPrincipalId"], operator_addr, neg["domain"]["chainId"])
        check(f"{name}: accepted == expected.accepted ({neg['expected']['accepted']})", res["accepted"] == neg["expected"]["accepted"], json.dumps(res))
        check(f"{name}: reason == expected.reason ({neg['expected']['reason']})", res["reason"] == neg["expected"]["reason"], json.dumps(res))
        check(f"{name}: Python's independent result matches the JSON's own stored result (JS/Python agree)",
              res["accepted"] == neg["result"]["accepted"] and res["reason"] == neg["result"]["reason"], json.dumps(res))
    check(f"exactly 15 negative vectors present", len(v["negatives"]) == 15, str(len(v["negatives"])))
    print()

    print("non-operator key sanity: the 'valid-signature-non-operator-key' vector recovers EXACTLY to")
    print("the non-operator wallet (not merely 'not the operator')")
    non_op_vec = next(n for n in v["negatives"] if n["name"] == "valid-signature-non-operator-key")
    dg_bytes, _, _ = eip712_digest(non_op_vec["domain"], non_op_vec["message"])
    sig_check = verify_d1(dg_bytes, non_op_vec["signature"]["full"], operator_addr)
    check("recovered == the non-operator wallet's own address", bool(sig_check["recovered"]) and sig_check["recovered"].lower() == non_operator_addr.lower(), sig_check.get("recovered"))
    print()

    print("informational: high-s malleable twin (r, n-s, v flipped), recovered WITHOUT the low-s gate")
    print("(ethers.recoverAddress itself refuses to compute this -- see the high-s vector's `note` in the")
    print("JSON; this is Python's unique contribution to these vectors, using its unconstrained ecrecover)")
    high_s_vec = next(n for n in v["negatives"] if n["name"] == "high-s")
    r_int = int(high_s_vec["signature"]["r"], 16)
    s_int = int(high_s_vec["signature"]["s"], 16)
    v_int = high_s_vec["signature"]["v"]
    check("the high-s signature's s is indeed > n/2 (non-canonical, as claimed)", s_int > SECP256K1_N2, hex(s_int))
    dg_bytes, _, _ = eip712_digest(high_s_vec["domain"], high_s_vec["message"])
    q = ecrecover(dg_bytes, r_int, s_int, v_int)  # UNGATED on purpose -- bypasses verify_d1's low-s refusal
    malleable_addr = address_from_point(q)
    check("high-s malleable twin recovers to the SAME address as the operator (confirmed independently, not merely asserted)",
          malleable_addr.lower() == operator_addr.lower(), malleable_addr)

    print()
    if failures:
        print(f"FAILED: {len(failures)} check(s): " + "; ".join(failures))
        return 1
    print("ALL CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
