// GENERATED by scripts/audit/seed-route-policy.mjs --emit-constants. DO NOT EDIT.
// Build-trusted route-policy manifest identity — the trust root for the runtime
// gate verifySeededPolicies (review finding #2). The gate requires the LIVE table
// to match these EXACTLY, so a stale/partial/tampered table cannot self-certify.
// Regenerate (and bump the manifest version) whenever the manifest changes.
export const EXPECTED_MANIFEST_VERSION = 3;
export const EXPECTED_MANIFEST_COUNT = 117;
export const EXPECTED_MANIFEST_DIGEST = "92fefe99cee4a9c9e28d98e2756020180a221c6c955cb937e2dd52b1f9fff28f";
