// GENERATED by scripts/audit/seed-route-policy.mjs --emit-constants. DO NOT EDIT.
// Build-trusted route-policy manifest identity — the trust root for the runtime
// gate verifySeededPolicies (review finding #2). The gate requires the LIVE table
// to match these EXACTLY, so a stale/partial/tampered table cannot self-certify.
// Regenerate (and bump the manifest version) whenever the manifest changes.
export const EXPECTED_MANIFEST_VERSION = 1;
export const EXPECTED_MANIFEST_COUNT = 112;
export const EXPECTED_MANIFEST_DIGEST = "e55955264c4d15b47d5344e1d828d023a3814d1a59da458b6fb9a365a5f25231";
