// GENERATED by scripts/audit/seed-route-policy.mjs --emit-constants. DO NOT EDIT.
// Build-trusted route-policy manifest identity — the trust root for the runtime
// gate verifySeededPolicies (review finding #2). The gate requires the LIVE table
// to match these EXACTLY, so a stale/partial/tampered table cannot self-certify.
// Regenerate (and bump the manifest version) whenever the manifest changes.
export const EXPECTED_MANIFEST_VERSION = 2;
export const EXPECTED_MANIFEST_COUNT = 114;
export const EXPECTED_MANIFEST_DIGEST = "57da591c8345b2d5505a8dc8fac490168f9039a53119e53fb28fccb2b01bac97";
