/**
 * Single source of truth for ContributorRole keccak256 hashes used as
 * `bytes32 roleTag` in MilestoneEscrow.Payout entries.
 *
 * On-chain: see `packages/contracts/src/RoleTags.sol` (codegen target —
 * regenerated by `pnpm --filter @pcc/contracts gen:role-tags`).
 *
 * Drift between this file and RoleTags.sol is a bug. CI must verify
 * they match (see `packages/contracts/test/RoleTagsCodegen.t.sol`).
 *
 * The `CONTRIBUTOR_ROLES` array is the canonical 11-value enum from
 * ADR-12 (2026-04-23, extended 2026-05-27 with `backend-author`). The
 * off-chain TS keccak256 hashes here MUST
 * equal the on-chain `bytes32` constants exposed by `RoleTags.sol`.
 *
 * Note: the legacy `designer` member of `ContributorRole` is intentionally
 * NOT included here — `designer` is deprecated (see ADR-12 §2.2) and was
 * never used as a roleTag on-chain. New records must map to
 * protocol-author / assembler / integrator.
 */

import { keccak_256 } from "@noble/hashes/sha3";
import type { ContributorRole } from "./types/story.js";

/**
 * The 10 canonical ContributorRole values (ADR-12). The order here is
 * load-bearing — the Solidity codegen iterates this array in order to
 * produce the `library RoleTags` constants. Reordering is a breaking
 * change for code review diffs but NOT for on-chain semantics (the
 * constant names + hashes are what matter, not declaration order).
 */
const CONTRIBUTOR_ROLES = [
  "operator",
  "verifier",
  "insurer",
  "integrator",
  "protocol-author",
  "model-author",
  "dataset-contributor",
  "backend-author",
  "curator",
  "assembler",
  "network-treasury",
] as const satisfies readonly ContributorRole[];

/**
 * Compute keccak256 of a UTF-8 string and return a 0x-prefixed 32-byte hex.
 * Uses `@noble/hashes` (browser-safe, no node:crypto dependency) to match
 * the existing SHA-256 helper's environment compatibility.
 */
function toRoleTag(role: string): `0x${string}` {
  const bytes = keccak_256(new TextEncoder().encode(role));
  const hex = Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return `0x${hex}` as `0x${string}`;
}

/**
 * `ROLE_TAGS` — keccak256 of each canonical ContributorRole string.
 *
 * These are the exact `bytes32` values written into Payout.roleTag on-chain.
 * Off-chain TS callers should import this map; on-chain Solidity callers
 * should use `RoleTags.<UPPER_SNAKE_CASE>` from `RoleTags.sol`.
 *
 * Keys mirror the 10-value `ContributorRole` enum (excluding the deprecated
 * `designer` alias). The "operator" tag is included for completeness even
 * though the on-chain settlement does NOT emit a SplitPayoutExecuted for
 * the operator residual (operator earnings flow through MilestoneReleased
 * to avoid double-counting).
 */
export const ROLE_TAGS = Object.fromEntries(
  CONTRIBUTOR_ROLES.map((role) => [role, toRoleTag(role)]),
) as Record<(typeof CONTRIBUTOR_ROLES)[number], `0x${string}`>;

/** Keys of `ROLE_TAGS`. Narrower than `ContributorRole` (excludes `designer`). */
export type RoleTagKey = keyof typeof ROLE_TAGS;

export { CONTRIBUTOR_ROLES };
