; CNC milling program
; Generated by Fusion 360
G90 ; absolute positioning
G21 ; metric
G0 Z5.0
G0 X0 Y0
G1 Z-1.0 F200
G1 X50 Y0 F500
G1 X50 Y50
G1 X0 Y50
G1 X0 Y0
G0 Z5.0
M5 ; spindle off
M30 ; end program
