; generated by PrusaSlicer 2.7.1
; filament_type = PLA
; layer_height = 0.2
; estimated printing time (normal mode) = 1h 23m 45s
; filament used [mm] = 4523.7
G28 ; home all axes
M104 S210 ; set nozzle temp
M140 S60 ; set bed temp
M109 S210 ; wait for nozzle temp
M190 S60 ; wait for bed temp
G1 Z0.2 F3000
G1 X10 Y10 E0.5 F1500
G1 X50 Y10 E2.0
G1 X50 Y50 E4.0
G1 X10 Y50 E6.0
G1 X10 Y10 E8.0
G1 Z0.4
G1 X10 Y10 E8.5
G1 X50 Y10 E10.0
M104 S0 ; turn off nozzle
M140 S0 ; turn off bed
G28 X Y ; home X and Y
M84 ; disable motors
