import type { StoreDB } from "../connection.js";
import { shopKernels, kernelDevices, capabilities } from "../schema/index.js";

/**
 * Seeds shop kernels, devices, and capabilities from gateway mock data.
 */
export function seedKernels(db: StoreDB): void {
  const now = new Date().toISOString();

  // ── Shop Kernels ────────────────────────────────────────────────

  db.insert(shopKernels)
    .values([
      {
        id: "kernel-nyc",
        name: "NYC MakerSpace",
        operatorAddress: "0x1111111111111111111111111111111111111111",
        location: { lat: 40.7128, lng: -74.006 },
        physicalAddress: "45 Industrial Rd, Brooklyn, NY 11222",
        maxAssuranceTier: 2,
        publicKey: "0x04a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8",
        reputation: 950,
        totalJobsCompleted: 127,
        status: "online",
        registeredAt: "2025-06-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-sf",
        name: "SF Precision Workshop",
        operatorAddress: "0x2222222222222222222222222222222222222222",
        location: { lat: 37.7749, lng: -122.4194 },
        physicalAddress: "200 Folsom St, San Francisco, CA 94105",
        maxAssuranceTier: 3,
        publicKey: "0x04b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9",
        reputation: 870,
        totalJobsCompleted: 89,
        status: "online",
        registeredAt: "2025-08-15T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-la",
        name: "LA Fab Lab",
        operatorAddress: "0x3333333333333333333333333333333333333333",
        location: { lat: 34.0522, lng: -118.2437 },
        physicalAddress: "800 Maple Ave, Los Angeles, CA 90015",
        maxAssuranceTier: 1,
        publicKey: "0x04c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
        reputation: 720,
        totalJobsCompleted: 42,
        status: "offline",
        registeredAt: "2025-10-01T00:00:00Z",
        lastHeartbeat: "2026-03-08T12:00:00Z",
        version: "1.3.2",
      },
      {
        id: "kernel-biolab-01",
        name: "Biolab Alpha",
        operatorAddress: "0x4444444444444444444444444444444444444444",
        location: { lat: 42.3601, lng: -71.0589 },
        physicalAddress: "100 Research Dr, Cambridge, MA 02139",
        maxAssuranceTier: 2,
        publicKey: "0x04d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1",
        reputation: 900,
        totalJobsCompleted: 58,
        status: "online",
        registeredAt: "2025-09-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      // ── Biotech / Neurotech Kernels ──────────────────────────────
      {
        id: "kernel-neurolab",
        name: "NeuroLab SOMA",
        operatorAddress: "0x5555555555555555555555555555555555555555",
        location: { lat: 37.7785, lng: -122.3950 },
        physicalAddress: "150 Townsend St, SOMA, San Francisco, CA 94107",
        maxAssuranceTier: 3,
        publicKey: "0x04e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
        reputation: 940,
        totalJobsCompleted: 73,
        status: "online",
        registeredAt: "2025-07-15T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-bioanalytica",
        name: "BioAnalytica Mission",
        operatorAddress: "0x6666666666666666666666666666666666666666",
        location: { lat: 37.7599, lng: -122.4148 },
        physicalAddress: "2200 Mission St, San Francisco, CA 94110",
        maxAssuranceTier: 2,
        publicKey: "0x04f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3",
        reputation: 880,
        totalJobsCompleted: 65,
        status: "online",
        registeredAt: "2025-08-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-frontier-4f",
        name: "Frontier Tower 4F Lab",
        operatorAddress: "0x7777777777777777777777777777777777777777",
        location: { lat: 37.7836, lng: -122.4089 },
        physicalAddress: "995 Market St, 4th Floor, San Francisco, CA 94103",
        maxAssuranceTier: 1,
        publicKey: "0x04a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4",
        reputation: 760,
        totalJobsCompleted: 31,
        status: "online",
        registeredAt: "2025-11-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      // ── NanoClaw — Opentrons OT-2 Liquid Handler ──────────────────
      {
        id: "kernel-nanoclaw",
        name: "NanoClaw OT-2",
        operatorAddress: "0x8888888888888888888888888888888888888888",
        location: { lat: 37.7836, lng: -122.4089 },
        physicalAddress: "995 Market St, 4th Floor, San Francisco, CA 94103",
        maxAssuranceTier: 2,
        publicKey: "0x04b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5",
        reputation: 850,
        totalJobsCompleted: 0,
        status: "online",
        registeredAt: "2026-03-26T00:00:00Z",
        lastHeartbeat: now,
        version: "1.5.0",
      },
    ])
    .run();

  // ── Kernel Devices ──────────────────────────────────────────────

  db.insert(kernelDevices)
    .values([
      // NYC MakerSpace devices
      {
        id: "dev-fdm-prusa-mk4",
        kernelId: "kernel-nyc",
        type: "machine",
        model: "Prusa MK4",
        firmware: "5.1.0",
        status: "busy",
        contributesToCapabilities: ["cap-nyc-fdm"],
        lastUpdated: now,
      },
      {
        id: "dev-laser-epilog",
        kernelId: "kernel-nyc",
        type: "machine",
        model: "Epilog Fusion Pro 48",
        firmware: "3.2.1",
        status: "idle",
        contributesToCapabilities: ["cap-nyc-laser"],
        lastUpdated: now,
      },
      {
        id: "dev-cam-nyc-1",
        kernelId: "kernel-nyc",
        type: "camera",
        model: "Arducam IMX477",
        firmware: "2.0.0",
        status: "idle",
        contributesToCapabilities: ["cap-nyc-fdm", "cap-nyc-laser"],
        lastUpdated: now,
      },
      // SF Workshop devices
      {
        id: "dev-cnc-haas-vf2",
        kernelId: "kernel-sf",
        type: "machine",
        model: "Haas VF-2",
        firmware: "100.22.000.1000",
        status: "busy",
        contributesToCapabilities: ["cap-sf-cnc"],
        lastUpdated: now,
      },
      // Biolab devices
      {
        id: "dev-liquid-handler",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Hamilton STAR",
        firmware: "4.7.2",
        status: "idle",
        contributesToCapabilities: ["cap-bio-liquid"],
        lastUpdated: now,
      },
      {
        id: "dev-centrifuge",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Beckman Avanti J-26S",
        firmware: "7.0.1",
        status: "idle",
        contributesToCapabilities: ["cap-bio-centrifuge"],
        lastUpdated: now,
      },
      {
        id: "dev-hplc",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Agilent 1260 Infinity II",
        firmware: "C.01.10",
        status: "busy",
        contributesToCapabilities: ["cap-bio-hplc"],
        lastUpdated: now,
      },
      // ── NeuroLab SOMA devices ──────────────────────────────────
      {
        id: "dev-hplc-neuro",
        kernelId: "kernel-neurolab",
        type: "machine",
        model: "Agilent 1260 Infinity II",
        firmware: "C.01.10",
        status: "idle",
        contributesToCapabilities: ["cap-neuro-hplc"],
        lastUpdated: now,
      },
      {
        id: "dev-massspec-neuro",
        kernelId: "kernel-neurolab",
        type: "machine",
        model: "Waters Xevo TQ-XS",
        firmware: "4.2.1",
        status: "busy",
        contributesToCapabilities: ["cap-neuro-massspec"],
        lastUpdated: now,
      },
      {
        id: "dev-patchclamp-neuro",
        kernelId: "kernel-neurolab",
        type: "machine",
        model: "Molecular Devices MultiClamp 700B",
        firmware: "2.2.0",
        status: "idle",
        contributesToCapabilities: ["cap-neuro-ephys"],
        lastUpdated: now,
      },
      // ── BioAnalytica Mission devices ───────────────────────────
      {
        id: "dev-pcr-bioanalytica",
        kernelId: "kernel-bioanalytica",
        type: "machine",
        model: "Bio-Rad CFX96 Touch",
        firmware: "3.1",
        status: "busy",
        contributesToCapabilities: ["cap-bioanalytica-pcr"],
        lastUpdated: now,
      },
      {
        id: "dev-sequencer-bioanalytica",
        kernelId: "kernel-bioanalytica",
        type: "machine",
        model: "Oxford Nanopore MinION Mk1C",
        firmware: "22.05.7",
        status: "idle",
        contributesToCapabilities: ["cap-bioanalytica-sequencing"],
        lastUpdated: now,
      },
      {
        id: "dev-confocal-bioanalytica",
        kernelId: "kernel-bioanalytica",
        type: "machine",
        model: "Zeiss LSM 900",
        firmware: "3.5.093",
        status: "idle",
        contributesToCapabilities: ["cap-bioanalytica-microscopy"],
        lastUpdated: now,
      },
      {
        id: "dev-incubator-bioanalytica",
        kernelId: "kernel-bioanalytica",
        type: "machine",
        model: "Thermo Heracell VIOS 160i",
        firmware: "1.4.0",
        status: "idle",
        contributesToCapabilities: ["cap-bioanalytica-cellculture"],
        lastUpdated: now,
      },
      // ── Frontier Tower 4F Lab devices ──────────────────────────
      {
        id: "dev-sampleprep-frontier",
        kernelId: "kernel-frontier-4f",
        type: "machine",
        model: "Agilent Bravo Liquid Handler",
        firmware: "5.3.0",
        status: "idle",
        contributesToCapabilities: ["cap-frontier-sampleprep"],
        lastUpdated: now,
      },
      {
        id: "dev-fluorescence-frontier",
        kernelId: "kernel-frontier-4f",
        type: "machine",
        model: "Nikon Eclipse Ti2",
        firmware: "5.42.02",
        status: "busy",
        contributesToCapabilities: ["cap-frontier-microscopy"],
        lastUpdated: now,
      },
      {
        id: "dev-printer-frontier",
        kernelId: "kernel-frontier-4f",
        type: "machine",
        model: "HP DesignJet Z9+ 44in",
        firmware: "2406A",
        status: "idle",
        contributesToCapabilities: ["cap-frontier-2dprint"],
        lastUpdated: now,
      },
      {
        id: "dev-platereader-frontier",
        kernelId: "kernel-frontier-4f",
        type: "machine",
        model: "BioTek Synergy H1",
        firmware: "3.11.17",
        status: "idle",
        contributesToCapabilities: ["cap-frontier-assay"],
        lastUpdated: now,
      },
      // ── NanoClaw devices ──────────────────────────────────────────
      {
        id: "dev-ot2-nanoclaw",
        kernelId: "kernel-nanoclaw",
        type: "machine",
        model: "Opentrons OT-2",
        firmware: "2.18.0",
        status: "idle",
        contributesToCapabilities: ["cap-nanoclaw-liquid"],
        lastUpdated: now,
      },
      {
        id: "dev-cam-nanoclaw",
        kernelId: "kernel-nanoclaw",
        type: "camera",
        model: "Raspberry Pi Camera v3",
        firmware: "1.0.0",
        status: "idle",
        contributesToCapabilities: ["cap-nanoclaw-liquid"],
        lastUpdated: now,
      },
    ])
    .run();

  // ── Capabilities ────────────────────────────────────────────────

  db.insert(capabilities)
    .values([
      {
        id: "cap-nyc-fdm",
        kernelId: "kernel-nyc",
        type: "fdm",
        name: "Prusa MK4 FDM Printing",
        description: "Fused deposition modeling with PLA, PETG, ASA, PC materials",
        materials: ["PLA", "PETG", "ASA", "PC"],
        tolerances: { linear: "\u00b10.15mm", surface: "Ra 12.5" },
        envelope: { x: 250, y: 210, z: 220, unit: "mm" as const },
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "5.00", perMinute: "0.08", perGram: "0.12", minimum: "5.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 40.7128, lng: -74.006 },
        queueDepth: 2,
        tags: ["fdm", "3d-print", "prototyping"],
      },
      {
        id: "cap-nyc-laser",
        kernelId: "kernel-nyc",
        type: "laser-cut",
        name: "Epilog Fusion Pro Laser Cutting",
        description: "CO2 laser cutting and engraving",
        materials: ["Acrylic", "Wood", "Leather", "Paper"],
        tolerances: { linear: "\u00b10.05mm" },
        envelope: { x: 1219, y: 914, z: 100, unit: "mm" as const },
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "8.00", perMinute: "0.15", minimum: "8.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 40.7128, lng: -74.006 },
        queueDepth: 0,
        tags: ["laser", "cutting", "engraving"],
      },
      {
        id: "cap-sf-cnc",
        kernelId: "kernel-sf",
        type: "cnc-3axis",
        name: "Haas VF-2 CNC Milling",
        description: "3-axis CNC milling for metals and plastics",
        materials: ["Aluminum 6061", "Stainless 304", "Delrin", "Brass"],
        tolerances: { linear: "\u00b10.025mm", surface: "Ra 1.6", positional: "\u00b10.05mm" },
        envelope: { x: 762, y: 406, z: 508, unit: "mm" as const },
        assuranceTiers: [0, 1, 2, 3],
        pricing: { currency: "USDC", baseCost: "25.00", perMinute: "0.50", minimum: "25.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7749, lng: -122.4194 },
        queueDepth: 1,
        tags: ["cnc", "milling", "metals", "precision"],
      },
      {
        id: "cap-la-sla",
        kernelId: "kernel-la",
        type: "sla",
        name: "SLA Resin Printing",
        description: "Stereolithography resin printing",
        materials: ["Standard Resin", "Tough Resin", "Flexible Resin"],
        tolerances: { linear: "\u00b10.05mm", surface: "Ra 2.5" },
        envelope: { x: 145, y: 145, z: 185, unit: "mm" as const },
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "10.00", perCm3: "0.30", minimum: "10.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 34.0522, lng: -118.2437 },
        queueDepth: 0,
        tags: ["sla", "resin", "high-detail"],
      },
      // Biolab capabilities
      {
        id: "cap-bio-liquid",
        kernelId: "kernel-biolab-01",
        type: "liquid-handler",
        name: "Hamilton STAR Liquid Handling",
        description: "Automated liquid handling with serial dilution capability",
        materials: ["aqueous", "organic", "biological"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "15.00", perMinute: "0.25", minimum: "15.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 0,
        tags: ["liquid-handler", "biotech", "automation"],
      },
      {
        id: "cap-bio-centrifuge",
        kernelId: "kernel-biolab-01",
        type: "centrifuge",
        name: "Beckman High-Speed Centrifuge",
        description: "High-speed centrifugation for sample preparation",
        materials: ["biological", "chemical"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "10.00", perMinute: "0.20", minimum: "10.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 0,
        tags: ["centrifuge", "biotech", "sample-prep"],
      },
      {
        id: "cap-bio-hplc",
        kernelId: "kernel-biolab-01",
        type: "hplc",
        name: "Agilent HPLC Analysis",
        description: "High-performance liquid chromatography with UV detection",
        materials: ["biological", "chemical", "pharmaceutical"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "30.00", perMinute: "0.50", minimum: "30.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 1,
        tags: ["hplc", "biotech", "analysis", "chromatography"],
      },
      // ── NeuroLab SOMA capabilities ─────────────────────────────
      {
        id: "cap-neuro-hplc",
        kernelId: "kernel-neurolab",
        type: "hplc",
        name: "Agilent HPLC Neurochemical Analysis",
        description: "HPLC with fluorescence detection for neurotransmitter quantification",
        materials: ["biological", "chemical", "pharmaceutical"],
        assuranceTiers: [0, 1, 2, 3],
        pricing: { currency: "USDC", baseCost: "35.00", perMinute: "0.55", minimum: "35.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7785, lng: -122.3950 },
        queueDepth: 0,
        tags: ["hplc", "neurotech", "chromatography", "neurotransmitter"],
      },
      {
        id: "cap-neuro-massspec",
        kernelId: "kernel-neurolab",
        type: "mass-spec",
        name: "Waters Xevo Mass Spectrometry",
        description: "Triple-quad mass spectrometry for peptide and small molecule analysis",
        materials: ["biological", "chemical", "pharmaceutical"],
        assuranceTiers: [0, 1, 2, 3],
        pricing: { currency: "USDC", baseCost: "50.00", perMinute: "0.80", minimum: "50.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7785, lng: -122.3950 },
        queueDepth: 1,
        tags: ["mass-spec", "neurotech", "proteomics", "metabolomics"],
      },
      {
        id: "cap-neuro-ephys",
        kernelId: "kernel-neurolab",
        type: "electrophysiology",
        name: "MultiClamp Patch Clamp Electrophysiology",
        description: "Whole-cell and single-channel patch clamp recording for neural tissue",
        materials: ["biological", "neural-tissue", "cell-culture"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "75.00", perMinute: "1.00", minimum: "75.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7785, lng: -122.3950 },
        queueDepth: 0,
        tags: ["electrophysiology", "neurotech", "patch-clamp", "neural"],
      },
      // ── BioAnalytica Mission capabilities ──────────────────────
      {
        id: "cap-bioanalytica-pcr",
        kernelId: "kernel-bioanalytica",
        type: "pcr",
        name: "Bio-Rad Real-Time PCR",
        description: "Quantitative real-time PCR with 6-channel fluorescence detection",
        materials: ["dna", "rna", "biological"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "20.00", perMinute: "0.30", minimum: "20.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7599, lng: -122.4148 },
        queueDepth: 2,
        tags: ["pcr", "qpcr", "biotech", "genomics"],
      },
      {
        id: "cap-bioanalytica-sequencing",
        kernelId: "kernel-bioanalytica",
        type: "sequencing",
        name: "Oxford Nanopore Long-Read Sequencing",
        description: "Real-time long-read DNA/RNA sequencing with adaptive sampling",
        materials: ["dna", "rna", "biological"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "100.00", perMinute: "0.10", minimum: "100.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7599, lng: -122.4148 },
        queueDepth: 0,
        tags: ["sequencing", "nanopore", "biotech", "genomics"],
      },
      {
        id: "cap-bioanalytica-cellculture",
        kernelId: "kernel-bioanalytica",
        type: "cell-culture",
        name: "Mammalian Cell Culture",
        description: "CO2 incubation for adherent and suspension cell lines (37C, 5% CO2)",
        materials: ["biological", "cell-line", "primary-cells"],
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "12.00", perMinute: "0.05", minimum: "12.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7599, lng: -122.4148 },
        queueDepth: 1,
        tags: ["cell-culture", "biotech", "incubation", "mammalian"],
      },
      {
        id: "cap-bioanalytica-microscopy",
        kernelId: "kernel-bioanalytica",
        type: "microscopy",
        name: "Zeiss Confocal Microscopy",
        description: "Laser scanning confocal microscopy with 4 laser lines and Z-stack capability",
        materials: ["biological", "tissue", "cell-culture"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "40.00", perMinute: "0.60", minimum: "40.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7599, lng: -122.4148 },
        queueDepth: 0,
        tags: ["microscopy", "confocal", "biotech", "imaging"],
      },
      // ── Frontier Tower 4F Lab capabilities ─────────────────────
      {
        id: "cap-frontier-sampleprep",
        kernelId: "kernel-frontier-4f",
        type: "sample-prep",
        name: "Automated Sample Preparation",
        description: "Automated liquid handling for sample prep, serial dilution, and plate formatting",
        materials: ["biological", "chemical", "aqueous"],
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "15.00", perMinute: "0.20", minimum: "15.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7836, lng: -122.4089 },
        queueDepth: 0,
        tags: ["sample-prep", "biotech", "automation", "liquid-handling"],
      },
      {
        id: "cap-frontier-microscopy",
        kernelId: "kernel-frontier-4f",
        type: "microscopy",
        name: "Fluorescence Microscopy",
        description: "Widefield fluorescence imaging with DAPI, GFP, RFP, and Cy5 filter sets",
        materials: ["biological", "tissue", "cell-culture"],
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "25.00", perMinute: "0.40", minimum: "25.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7836, lng: -122.4089 },
        queueDepth: 1,
        tags: ["microscopy", "fluorescence", "biotech", "imaging"],
      },
      {
        id: "cap-frontier-2dprint",
        kernelId: "kernel-frontier-4f",
        type: "2d-print",
        name: "Large Format Poster Printing",
        description: "44-inch wide-format printing for scientific posters and lab documentation",
        materials: ["paper", "glossy", "matte", "canvas"],
        assuranceTiers: [0],
        pricing: { currency: "USDC", baseCost: "8.00", perMinute: "0.10", minimum: "8.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7836, lng: -122.4089 },
        queueDepth: 0,
        tags: ["2d-print", "poster", "documentation"],
      },
      {
        id: "cap-frontier-assay",
        kernelId: "kernel-frontier-4f",
        type: "assay",
        name: "Multimode Plate Reader Assays",
        description: "Absorbance, fluorescence, and luminescence plate reading (6-384 well)",
        materials: ["biological", "chemical", "pharmaceutical"],
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "18.00", perMinute: "0.15", minimum: "18.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7836, lng: -122.4089 },
        queueDepth: 0,
        tags: ["assay", "plate-reader", "biotech", "screening"],
      },
      // ── NanoClaw capabilities ─────────────────────────────────────
      {
        id: "cap-nanoclaw-liquid",
        kernelId: "kernel-nanoclaw",
        type: "liquid-handler",
        name: "NanoClaw OT-2 Liquid Handling",
        description: "Automated liquid handling via Opentrons OT-2 — transfers, serial dilutions, plate formatting, mixing. Dual pipettes (P300 + P20), 11 deck slots, thermocycler/temperature/magnetic module support.",
        materials: ["aqueous", "organic", "biological", "chemical"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "10.00", perMinute: "0.15", minimum: "10.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7836, lng: -122.4089 },
        queueDepth: 0,
        tags: ["liquid-handler", "opentrons", "ot-2", "biotech", "automation", "nanoclaw"],
      },
    ])
    .run();
}
