import type { StoreDB } from "../connection.js";
import { shopKernels, kernelDevices, capabilities } from "../schema/index.js";

/**
 * Seeds shop kernels, devices, and capabilities from gateway mock data.
 */
export function seedKernels(db: StoreDB): void {
  const now = new Date().toISOString();

  // ── Shop Kernels ────────────────────────────────────────────────

  db.insert(shopKernels)
    .values([
      {
        id: "kernel-nyc",
        name: "NYC MakerSpace",
        operatorAddress: "0x1111111111111111111111111111111111111111",
        location: { lat: 40.7128, lng: -74.006 },
        physicalAddress: "45 Industrial Rd, Brooklyn, NY 11222",
        maxAssuranceTier: 2,
        publicKey: "0x04a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8",
        reputation: 950,
        totalJobsCompleted: 127,
        status: "online",
        registeredAt: "2025-06-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-sf",
        name: "SF Precision Workshop",
        operatorAddress: "0x2222222222222222222222222222222222222222",
        location: { lat: 37.7749, lng: -122.4194 },
        physicalAddress: "200 Folsom St, San Francisco, CA 94105",
        maxAssuranceTier: 3,
        publicKey: "0x04b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9",
        reputation: 870,
        totalJobsCompleted: 89,
        status: "online",
        registeredAt: "2025-08-15T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
      {
        id: "kernel-la",
        name: "LA Fab Lab",
        operatorAddress: "0x3333333333333333333333333333333333333333",
        location: { lat: 34.0522, lng: -118.2437 },
        physicalAddress: "800 Maple Ave, Los Angeles, CA 90015",
        maxAssuranceTier: 1,
        publicKey: "0x04c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
        reputation: 720,
        totalJobsCompleted: 42,
        status: "offline",
        registeredAt: "2025-10-01T00:00:00Z",
        lastHeartbeat: "2026-03-08T12:00:00Z",
        version: "1.3.2",
      },
      {
        id: "kernel-biolab-01",
        name: "Biolab Alpha",
        operatorAddress: "0x4444444444444444444444444444444444444444",
        location: { lat: 42.3601, lng: -71.0589 },
        physicalAddress: "100 Research Dr, Cambridge, MA 02139",
        maxAssuranceTier: 2,
        publicKey: "0x04d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1",
        reputation: 900,
        totalJobsCompleted: 58,
        status: "online",
        registeredAt: "2025-09-01T00:00:00Z",
        lastHeartbeat: now,
        version: "1.4.0",
      },
    ])
    .run();

  // ── Kernel Devices ──────────────────────────────────────────────

  db.insert(kernelDevices)
    .values([
      // NYC MakerSpace devices
      {
        id: "dev-fdm-prusa-mk4",
        kernelId: "kernel-nyc",
        type: "machine",
        model: "Prusa MK4",
        firmware: "5.1.0",
        status: "busy",
        contributesToCapabilities: ["cap-nyc-fdm"],
        lastUpdated: now,
      },
      {
        id: "dev-laser-epilog",
        kernelId: "kernel-nyc",
        type: "machine",
        model: "Epilog Fusion Pro 48",
        firmware: "3.2.1",
        status: "idle",
        contributesToCapabilities: ["cap-nyc-laser"],
        lastUpdated: now,
      },
      {
        id: "dev-cam-nyc-1",
        kernelId: "kernel-nyc",
        type: "camera",
        model: "Arducam IMX477",
        firmware: "2.0.0",
        status: "idle",
        contributesToCapabilities: ["cap-nyc-fdm", "cap-nyc-laser"],
        lastUpdated: now,
      },
      // SF Workshop devices
      {
        id: "dev-cnc-haas-vf2",
        kernelId: "kernel-sf",
        type: "machine",
        model: "Haas VF-2",
        firmware: "100.22.000.1000",
        status: "busy",
        contributesToCapabilities: ["cap-sf-cnc"],
        lastUpdated: now,
      },
      // Biolab devices
      {
        id: "dev-liquid-handler",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Hamilton STAR",
        firmware: "4.7.2",
        status: "idle",
        contributesToCapabilities: ["cap-bio-liquid"],
        lastUpdated: now,
      },
      {
        id: "dev-centrifuge",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Beckman Avanti J-26S",
        firmware: "7.0.1",
        status: "idle",
        contributesToCapabilities: ["cap-bio-centrifuge"],
        lastUpdated: now,
      },
      {
        id: "dev-hplc",
        kernelId: "kernel-biolab-01",
        type: "machine",
        model: "Agilent 1260 Infinity II",
        firmware: "C.01.10",
        status: "busy",
        contributesToCapabilities: ["cap-bio-hplc"],
        lastUpdated: now,
      },
    ])
    .run();

  // ── Capabilities ────────────────────────────────────────────────

  db.insert(capabilities)
    .values([
      {
        id: "cap-nyc-fdm",
        kernelId: "kernel-nyc",
        type: "fdm",
        name: "Prusa MK4 FDM Printing",
        description: "Fused deposition modeling with PLA, PETG, ASA, PC materials",
        materials: ["PLA", "PETG", "ASA", "PC"],
        tolerances: { linear: "\u00b10.15mm", surface: "Ra 12.5" },
        envelope: { x: 250, y: 210, z: 220, unit: "mm" as const },
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "5.00", perMinute: "0.08", perGram: "0.12", minimum: "5.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 40.7128, lng: -74.006 },
        queueDepth: 2,
        tags: ["fdm", "3d-print", "prototyping"],
      },
      {
        id: "cap-nyc-laser",
        kernelId: "kernel-nyc",
        type: "laser-cut",
        name: "Epilog Fusion Pro Laser Cutting",
        description: "CO2 laser cutting and engraving",
        materials: ["Acrylic", "Wood", "Leather", "Paper"],
        tolerances: { linear: "\u00b10.05mm" },
        envelope: { x: 1219, y: 914, z: 100, unit: "mm" as const },
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "8.00", perMinute: "0.15", minimum: "8.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 40.7128, lng: -74.006 },
        queueDepth: 0,
        tags: ["laser", "cutting", "engraving"],
      },
      {
        id: "cap-sf-cnc",
        kernelId: "kernel-sf",
        type: "cnc-3axis",
        name: "Haas VF-2 CNC Milling",
        description: "3-axis CNC milling for metals and plastics",
        materials: ["Aluminum 6061", "Stainless 304", "Delrin", "Brass"],
        tolerances: { linear: "\u00b10.025mm", surface: "Ra 1.6", positional: "\u00b10.05mm" },
        envelope: { x: 762, y: 406, z: 508, unit: "mm" as const },
        assuranceTiers: [0, 1, 2, 3],
        pricing: { currency: "USDC", baseCost: "25.00", perMinute: "0.50", minimum: "25.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 37.7749, lng: -122.4194 },
        queueDepth: 1,
        tags: ["cnc", "milling", "metals", "precision"],
      },
      {
        id: "cap-la-sla",
        kernelId: "kernel-la",
        type: "sla",
        name: "SLA Resin Printing",
        description: "Stereolithography resin printing",
        materials: ["Standard Resin", "Tough Resin", "Flexible Resin"],
        tolerances: { linear: "\u00b10.05mm", surface: "Ra 2.5" },
        envelope: { x: 145, y: 145, z: 185, unit: "mm" as const },
        assuranceTiers: [0, 1],
        pricing: { currency: "USDC", baseCost: "10.00", perCm3: "0.30", minimum: "10.00" },
        availability: { timezone: "America/Los_Angeles", windows: {} },
        location: { lat: 34.0522, lng: -118.2437 },
        queueDepth: 0,
        tags: ["sla", "resin", "high-detail"],
      },
      // Biolab capabilities
      {
        id: "cap-bio-liquid",
        kernelId: "kernel-biolab-01",
        type: "liquid-handler",
        name: "Hamilton STAR Liquid Handling",
        description: "Automated liquid handling with serial dilution capability",
        materials: ["aqueous", "organic", "biological"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "15.00", perMinute: "0.25", minimum: "15.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 0,
        tags: ["liquid-handler", "biotech", "automation"],
      },
      {
        id: "cap-bio-centrifuge",
        kernelId: "kernel-biolab-01",
        type: "centrifuge",
        name: "Beckman High-Speed Centrifuge",
        description: "High-speed centrifugation for sample preparation",
        materials: ["biological", "chemical"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "10.00", perMinute: "0.20", minimum: "10.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 0,
        tags: ["centrifuge", "biotech", "sample-prep"],
      },
      {
        id: "cap-bio-hplc",
        kernelId: "kernel-biolab-01",
        type: "hplc",
        name: "Agilent HPLC Analysis",
        description: "High-performance liquid chromatography with UV detection",
        materials: ["biological", "chemical", "pharmaceutical"],
        assuranceTiers: [0, 1, 2],
        pricing: { currency: "USDC", baseCost: "30.00", perMinute: "0.50", minimum: "30.00" },
        availability: { timezone: "America/New_York", windows: {} },
        location: { lat: 42.3601, lng: -71.0589 },
        queueDepth: 1,
        tags: ["hplc", "biotech", "analysis", "chromatography"],
      },
    ])
    .run();
}
